import type { Lesson } from "@/lib/lesson-catalog";
import { getIndustrialLessonArtwork } from "@/lib/industrial-lesson-art";

const code = (...lines: string[]) => lines.join("\n");

const lessonCore: Array<
  Omit<Lesson, "objectives" | "concept" | "codeWalkthrough" | "expected" | "troubleshooting">
> = [
  {
    slug: "01-six-axis-articulated-arm",
    title: "Six-axis articulated arm",
    duration: "60–90 min",
    summary:
      "Model six revolute joints, validate targets and send a guarded trajectory through ros2_control.",
    steps: [
      "Use mock hardware and confirm every URDF joint limit before enabling a controller.",
      "Start robot_state_publisher, controller_manager, joint_state_broadcaster and joint_trajectory_controller.",
      "Inspect claimed interfaces with ros2 control list_hardware_interfaces and confirm both controllers are active.",
      "Compile the C++ client, send a reduced-range goal and inspect the action result.",
    ],
    example: code(
      `using Follow = control_msgs::action::FollowJointTrajectory;`,
      `// Give the long action type a short alias named Follow.`,
      `const std::array<double, 6> target{0.0, -0.35, 0.55, 0.0, 0.25, 0.0};`,
      `// A fixed-size, read-only target: one angle in radians for each of the six joints.`,
      `if (!limits_.contains(target) || !client_->wait_for_action_server(2s)) {`,
      `  // Stop if the target is outside the joint limits, or the controller's action server is not available within 2 seconds.`,
      `  RCLCPP_WARN(get_logger(), "target rejected or controller unavailable");`,
      `  // Log a warning that explains why nothing will be sent.`,
      `  return;`,
      `  // Leave the function so no command reaches the robot.`,
      `}`,
      `// End of the guard; from here on the target is valid and the server is ready.`,
      `trajectory_msgs::msg::JointTrajectory trajectory;`,
      `// Create an empty trajectory message.`,
      `trajectory.joint_names = {"joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"};`,
      `// Name the joints, in the same order as the target values and as the controller expects.`,
      `trajectory_msgs::msg::JointTrajectoryPoint point;`,
      `// Create one waypoint of the trajectory.`,
      `point.positions.assign(target.begin(), target.end());`,
      `// Copy the six target angles into the waypoint.`,
      `point.time_from_start.sec = 4;`,
      `// Allow 4 seconds to reach this waypoint, which keeps the motion slow and gentle.`,
      `trajectory.points.push_back(point);`,
      `// Add the waypoint to the trajectory.`,
      `Follow::Goal goal; goal.trajectory = trajectory;`,
      `// Create the action goal and attach the trajectory to it.`,
      `client_->async_send_goal(goal, result_aware_options());`,
      `// Send the goal without blocking; the options object handles the response and result later.`,
    ),
    exercise:
      "Create an ament_cmake package named arm_trajectory_client. Reject targets outside the URDF limits before creating the goal, then run three valid simulated poses and one rejected pose.",
    checklist: [
      "Joint names match the controller",
      "Targets use radians and stay inside URDF limits",
      "The controller is active before a goal is sent",
      "A rejected target never reaches the server",
    ],
    notes: [
      "Command simulation or mock hardware only.",
      "Manufacturer commissioning, payload, braking-distance and safety instructions always take priority.",
    ],
    sourceLabel: "Joint trajectory controller",
    sourceHref:
      "https://control.ros.org/lyrical/doc/ros2_controllers/joint_trajectory_controller/doc/userdoc.html",
  },
  {
    slug: "02-scara-robot",
    title: "SCARA robot",
    duration: "60–90 min",
    summary:
      "Coordinate planar joints, a vertical axis and tool rotation for a staged assembly cycle.",
    steps: [
      "Describe revolute, prismatic and fixed tool joints in xacro.",
      "Publish the model and verify base_link to tool0 with tf2_echo.",
      "Represent each pick/place phase as a named joint target in radians and metres.",
      "Execute approach, descend, retract and place goals sequentially, checking each result.",
    ],
    example: code(
      `std::vector<std::array<double, 4>> cycle{`,
      `// A list of poses; each pose holds four numbers: two joint angles (rad), the vertical axis (m), and tool rotation (rad).`,
      `  {0.25, 0.70, 0.00, 0.0},`,
      `  // Approach: arms positioned above the pick point, vertical axis at its raised position.`,
      `  {0.25, 0.70, -0.08, 0.0},`,
      `  // Descend: same position, but the vertical axis lowers by 0.08 m.`,
      `  {0.25, 0.70, 0.00, 0.0},`,
      `  // Retract: lift back up to the raised height.`,
      `  {-0.30, 0.55, -0.05, 1.57}`,
      `  // Place: swing to the drop location, lower slightly, and rotate the tool by about 90 degrees (1.57 rad).`,
      `};`,
      `// End of the cycle list.`,
      `for (const auto & target : cycle) {`,
      `  // Visit each pose in order, reading it through a const reference so nothing is copied or changed.`,
      `  if (!within_limits(target)) throw std::range_error("unsafe target");`,
      `  // Refuse to continue if this pose is outside the allowed range, by raising an error.`,
      `  send_and_wait(target);`,
      `  // Send the pose to the controller and wait for its result before starting the next one.`,
      `}`,
      `// End of the loop; the phases ran strictly one after another.`,
    ),
    exercise:
      "Build a simulated four-stage pick-and-place cycle. Add a tool offset frame and prove its pose with tf2_echo before motion.",
    checklist: [
      "Prismatic values use metres",
      "The tool frame is connected",
      "Each phase waits for the prior result",
      "Invalid workspaces are rejected",
    ],
    notes: ["Collision and work-envelope checks remain necessary for planar motion."],
    sourceLabel: "ROS 2 tf2 tutorials",
    sourceHref: "https://docs.ros.org/en/lyrical/Tutorials/Intermediate/Tf2/Tf2-Main.html",
  },
  {
    slug: "03-delta-parallel-robot",
    title: "Delta parallel robot",
    duration: "60–90 min",
    summary:
      "Build a timing-aware conveyor simulation without treating generic code as vendor kinematics.",
    steps: [
      "Use a tested kinematics adapter for the exact robot geometry.",
      "Subscribe to stamped detections and reject stale observations.",
      "Use steady time for local deadlines and ROS time for graph data.",
      "Cancel the pick action when an object leaves the reachable window.",
    ],
    example: code(
      `void detection_callback(const geometry_msgs::msg::PointStamped & msg) {`,
      `  // Runs every time a stamped object detection arrives; msg is read-only and not copied.`,
      `  const auto stamp = rclcpp::Time(msg.header.stamp);`,
      `  // Convert the message's timestamp into a ROS time value.`,
      `  const auto age = now() - stamp;`,
      `  // Work out how old the detection is by subtracting its stamp from the current time.`,
      `  if (age < rclcpp::Duration::from_seconds(-0.01) ||`,
      `      age > rclcpp::Duration::from_seconds(0.10)) return;`,
      `  // Ignore the detection if it is from the future (more than 10 ms) or older than 100 ms, since stale data gives wrong picks.`,
      `  const auto target = kinematics_.solve(msg.point);`,
      `  // Ask the kinematics adapter for the joint target that reaches this point; it may return "no solution".`,
      `  if (!target || !limits_.contains(*target)) return;`,
      `  // Ignore the detection if the point is unreachable or the joint target is outside the allowed limits.`,
      `  pick_action_->async_send_goal(make_pick_goal(*target));`,
      `  // Send a pick goal to the action server without blocking the callback.`,
      `}`,
      `// End of the callback.`,
    ),
    exercise:
      "Replay stamped conveyor detections. Count accepted, stale and unreachable targets, then document the tested latency budget.",
    checklist: [
      "Detections include frame and timestamp",
      "Stale data is rejected",
      "Kinematics failure sends no command",
      "The action can be canceled",
    ],
    notes: [
      "Never copy kinematic constants between delta models; geometry and calibration are machine-specific.",
    ],
    sourceLabel: "ROS clock and time",
    sourceHref: "https://design.ros2.org/articles/clock_and_time.html",
  },
  {
    slug: "04-cartesian-gantry",
    title: "Cartesian gantry",
    duration: "60–90 min",
    summary:
      "Home three linear axes and command bounded XYZ trajectories with explicit state transitions.",
    steps: [
      "Represent X, Y and Z as prismatic joints with metre limits.",
      "Create unconfigured, homing, ready, moving and fault states.",
      "Expose homing progress and refuse transitions from an unsafe state.",
      "Send trajectories only when every axis is homed and controllers are active.",
    ],
    example: code(
      `enum class GantryState { unconfigured, homing, ready, moving, fault };`,
      `// The named states the gantry can be in; enum class stops these names from mixing with others.`,
      `bool request_move(const std::array<double, 3> & xyz) {`,
      `  // Try to start a move to an X, Y, Z position in metres; returns true only if the request was accepted.`,
      `  if (state_ != GantryState::ready || !limits_.contains(xyz)) return false;`,
      `  // Refuse if the gantry is not homed and ready, or if the target is outside the soft limits.`,
      `  auto options = GoalOptions{};`,
      `  // Create the options object that holds callbacks for this goal.`,
      `  options.goal_response_callback = [this](const auto & handle) {`,
      `    // Runs when the server accepts or rejects the goal; this captures the current object so it can change state_.`,
      `    state_ = handle ? GantryState::moving : GantryState::ready;`,
      `    // If the goal was accepted (handle is valid), we are moving; otherwise go back to ready.`,
      `  };`,
      `  // End of the response callback.`,
      `  options.result_callback = [this](const auto & result) {`,
      `    // Runs when the motion finishes, gives the outcome in result.`,
      `    state_ = result.code == ResultCode::SUCCEEDED ? GantryState::ready : GantryState::fault;`,
      `    // Success returns to ready; any other outcome puts the gantry in fault so recovery must be explicit.`,
      `  };`,
      `  // End of the result callback.`,
      `  trajectory_client_->async_send_goal(make_goal(xyz), options);`,
      `  // Build the goal from the position and send it without blocking, with the callbacks attached.`,
      `  return true;`,
      `  // Tell the caller the request was accepted.`,
      `}`,
      `// End of the function.`,
    ),
    exercise:
      "Implement simulated homing and a motion request. Prove that pre-home and beyond-limit moves are refused.",
    checklist: [
      "Linear values use metres",
      "Motion is impossible before homing",
      "Soft limits are conservative",
      "Fault recovery is explicit",
    ],
    notes: ["Real homing direction, speed and switch polarity must come from the machine manual."],
    sourceLabel: "Managed node lifecycle",
    sourceHref: "https://design.ros2.org/articles/node_lifecycle.html",
  },
  {
    slug: "05-humanoid-platform",
    title: "Humanoid platform",
    duration: "60–90 min",
    summary:
      "Monitor orientation and coordinate joint groups inside a simulation-only stability envelope.",
    steps: [
      "Split the model into torso, leg and arm groups.",
      "Subscribe to sensor_msgs/Imu and joint_states with sensor QoS.",
      "Validate and convert orientation without blocking a callback.",
      "Cancel active goals and hold the simulated pose after a threshold breach.",
    ],
    example: code(
      `void imu_callback(const sensor_msgs::msg::Imu & msg) {`,
      `  // Runs for every IMU (orientation sensor) message that arrives.`,
      `  tf2::Quaternion q(msg.orientation.x, msg.orientation.y, msg.orientation.z, msg.orientation.w);`,
      `  // Build a quaternion from the four orientation components in the message.`,
      `  if (std::abs(q.length2() - 1.0) > 0.01) return;`,
      `  // A valid orientation quaternion has length 1; skip the sample if its squared length is off by more than 0.01.`,
      `  double roll{}, pitch{}, yaw{};`,
      `  // Declare three angles, all starting at zero, to receive the result.`,
      `  tf2::Matrix3x3(q).getRPY(roll, pitch, yaw);`,
      `  // Convert the quaternion to roll, pitch and yaw angles in radians.`,
      `  if (std::abs(roll) > max_tilt_ || std::abs(pitch) > max_tilt_) {`,
      `    // If the platform leans further than the allowed tilt in either direction...`,
      `    cancel_active_goal(); publish_training_hold();`,
      `    // ...cancel the running motion goal and publish a hold message for the simulated pose.`,
      `  }`,
      `  // End of the tilt check.`,
      `}`,
      `// End of the callback; nothing here sleeps or blocks.`,
    ),
    exercise:
      "Replay IMU samples into a simulated posture monitor and verify normal, invalid-quaternion and excessive-tilt cases.",
    checklist: [
      "Quaternion validity is checked",
      "Thresholds are bounded parameters",
      "Callbacks never sleep",
      "The test remains simulation-only",
    ],
    notes: ["This monitor is not a balance controller and must not stabilize hardware."],
    sourceLabel: "ROS 2 QoS settings",
    sourceHref:
      "https://docs.ros.org/en/lyrical/Concepts/Intermediate/About-Quality-of-Service-Settings.html",
  },
  {
    slug: "06-collaborative-robot",
    title: "Collaborative robot",
    duration: "60–90 min",
    summary:
      "Build an operator-aware command gate while keeping certified safety outside application code.",
    steps: [
      "Document that collaboration requires an application risk assessment.",
      "Subscribe to a simulated protected-zone state and gate new goals.",
      "Validate speed against a conservative training limit.",
      "Record blocked requests and test recovery after the zone clears.",
    ],
    example: code(
      `bool command_allowed(double speed) const {`,
      `  // A read-only check (const) that decides whether a motion request may proceed.`,
      `  return zone_clear_.load(std::memory_order_acquire) &&`,
      `  // Read the protected-zone flag safely across threads; the zone must be clear...`,
      `         speed >= 0.0 && speed <= training_speed_limit_;`,
      `  // ...and the speed must be non-negative and not above the conservative training limit.`,
      `}`,
      `// End of the check; if the zone state was never received, the flag stays false and the command is blocked.`,
      `void request_motion(const MotionRequest & request) {`,
      `  // Entry point for a motion request from elsewhere in the program.`,
      `  if (!command_allowed(request.speed)) {`,
      `    // Run the gate; enter this block if the command is not allowed.`,
      `    RCLCPP_WARN(get_logger(), "motion blocked"); return;`,
      `    // Log that the motion was blocked, then leave without sending anything.`,
      `  }`,
      `  // End of the blocked branch.`,
      `  motion_client_->async_send_goal(to_goal(request));`,
      `  // Only allowed requests reach here: convert the request into an action goal and send it without blocking.`,
      `}`,
      `// End of the function.`,
    ),
    exercise:
      "Create a protected-zone publisher and command gate. Prove that occupied-zone and over-speed requests produce no action goal.",
    checklist: [
      "Missing state defaults to blocked",
      "No safety state comes from UI alone",
      "Blocked commands are logged",
      "ROS is not presented as a safety controller",
    ],
    notes: [
      "Emergency stop, safe torque off and protective separation require validated safety equipment and procedures.",
    ],
    sourceLabel: "ROS 2 security",
    sourceHref: "https://docs.ros.org/en/lyrical/Concepts/Intermediate/About-Security.html",
  },
  {
    slug: "07-autonomous-mobile-robot",
    title: "Autonomous mobile robot",
    duration: "60–90 min",
    summary:
      "Transform stamped goals into map and run cancellable simulated missions with recorded evidence.",
    steps: [
      "Confirm map, odom and base_link form one TF tree.",
      "Transform PoseStamped goals into map before validation.",
      "Send valid goals through an action client and publish mission state.",
      "Cancel on timeout, then record odometry and scan topics.",
    ],
    example: code(
      `geometry_msgs::msg::PoseStamped map_goal;`,
      `// Create a variable that will hold the goal expressed in the map frame.`,
      `if (rclcpp::Time(input_goal.header.stamp) > now() + rclcpp::Duration::from_seconds(0.1)) return;`,
      `// Reject goals stamped more than 0.1 s in the future, because such timestamps are not trustworthy.`,
      `try {`,
      `  // Start a block where a transform lookup may throw an error.`,
      `  map_goal = tf_buffer_->transform(input_goal, "map", tf2::durationFromSec(0.2));`,
      `  // Convert the goal into the map frame, waiting up to 0.2 s for the needed transform data.`,
      `} catch (const tf2::TransformException & error) {`,
      `  // Runs if the frame is unknown or no transform is available in time.`,
      `  RCLCPP_WARN(get_logger(), "goal rejected: %s", error.what()); return;`,
      `  // Log the reason for the failure and stop; nothing moves.`,
      `}`,
      `// End of the try/catch.`,
      `if (!valid_orientation(map_goal.pose.orientation) ||`,
      `    !workspace_.contains(map_goal.pose.position) ||`,
      `    !costmap_.is_free(map_goal.pose.position)) return;`,
      `// Reject the goal unless its orientation is valid, it lies inside the allowed workspace, and the costmap says the spot is free.`,
      `navigate_client_->async_send_goal(make_goal(map_goal));`,
      `// The goal passed every check: build the navigation goal and send it without blocking.`,
    ),
    exercise:
      "Build a simulated mission dispatcher. Test a valid goal, unknown frame, out-of-bounds goal and cancellation.",
    checklist: [
      "The map to base frame chain exists",
      "Unknown frames fail without motion",
      "The action supports cancellation",
      "A bag captures failure evidence",
    ],
    notes: ["Pin and document the navigation package version tested for a real deployment."],
    sourceLabel: "C++ tf2 listener",
    sourceHref:
      "https://docs.ros.org/en/lyrical/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Listener-Cpp.html",
  },
];

export const industrialLessons: Lesson[] = lessonCore.map((lesson) => ({
  ...lesson,
  image: getIndustrialLessonArtwork(lesson.slug),
  objectives: [
    `Explain the motion structure of a ${lesson.title.toLowerCase()}`,
    "Trace a command from validation to the ROS 2 controller or action server",
    "Prove unsafe or invalid input is rejected before simulated motion",
  ],
  concept: [
    `${lesson.summary} The robot model, coordinate frames, joint limits, controller state, and command interface form one chain. A mistake anywhere in that chain can make a numerically valid target physically wrong.`,
    "The example is application-level training code, not a safety function or vendor commissioning procedure. Work with simulation or mock hardware first, use conservative limits, and treat every rejected command as useful evidence.",
  ],
  codeWalkthrough: [
    "The input is validated before a goal is built, so bad data cannot reach the motion interface.",
    "ROS 2 messages and actions carry typed commands; units, joint order, frame names, and timestamps are part of that contract.",
    "Asynchronous calls keep the node responsive, but production code must also inspect acceptance, feedback, result, timeout, and cancellation.",
  ],
  expected: [
    "The simulated system accepts valid, reduced-range input and reports a successful result.",
    "At least one deliberately invalid input is rejected without sending a motion goal.",
    "The learner can identify the frame, unit, limit, and controller involved in the command.",
  ],
  troubleshooting: [
    {
      symptom: "The action server or controller is unavailable.",
      fix: "List controllers and actions, confirm the expected controller is active, and compare the configured action name with the client.",
    },
    {
      symptom: "The model moves in the wrong direction or to the wrong pose.",
      fix: "Stop the simulation. Check joint order, radians versus metres, frame transforms, and URDF joint origins before changing gains or limits.",
    },
  ],
}));
