import { cpp, sh, type CppPhase } from "./types";

export const phase2: CppPhase = {
  number: 2,
  title: "Phase 2 — Object-Oriented Programming",
  blurb: "The object model that ROS 2 is built on: encapsulation, inheritance, polymorphism, headers and error handling.",
  lessons: [
    {
      title: "Encapsulation",
      detail: "Private data, a small public interface, and class invariants.",
      time: "45–75 min",
      concept: [
        "Encapsulation means an object's data is private and can only be changed through methods that keep it valid. The rule that must always be true for a valid object is called its invariant, for example 'the joint angle is always inside its limits'.",
        "A small public interface is easy to test and lets you change the inside later without breaking callers. Expose behaviour (move_to) rather than raw data (a public angle variable).",
      ],
      example: cpp(
        ["class Joint {", "A joint that guarantees its angle stays inside the limits."],
        ["public:", "The public interface starts here."],
        ["  Joint(double low, double high) : low_{low}, high_{high} {}", "Store the limits once, at construction."],
        ["  bool move_to(double angle) {", "The only way to change the angle."],
        ["    if (angle < low_ || angle > high_) return false;", "Refuse targets that would break the invariant."],
        ["    angle_ = angle;", "Accept a valid target."],
        ["    return true;", "Tell the caller it worked."],
        ["  }", "End of move_to."],
        ["  double angle() const { return angle_; }", "Read-only access to the current angle."],
        ["private:", "Nobody outside the class can touch the data below."],
        ["  double low_, high_;", "The allowed range."],
        ["  double angle_{0.0};", "Current angle, starting inside the range."],
        ["};", "End of the class."],
      ),
      exercise:
        "Write a Joint class with limits, a move_to that rejects illegal targets, and a const angle(). Write a test that tries a target above the limit and confirms the angle is unchanged.",
    },
    {
      title: "Inheritance",
      detail: "Base and derived classes, protected members, and the 'is-a' rule.",
      time: "45–75 min",
      concept: [
        "Inheritance lets a derived class reuse and extend a base class: class ServoMotor : public Motor. Use it only for a true 'is-a' relationship, where a ServoMotor can be used anywhere a Motor is expected.",
        "The derived constructor must call the base constructor first. Members marked protected are visible to derived classes but not to outsiders. Prefer composition (a member object) when the relationship is 'has-a'.",
      ],
      example: cpp(
        ["class Motor {", "The base class with behaviour every motor shares."],
        ["public:", "Public interface."],
        ["  explicit Motor(int id) : id_{id} {}", "Base constructor stores the ID."],
        ["  int id() const { return id_; }", "Shared getter."],
        ["protected:", "Visible to derived classes, hidden from everyone else."],
        ["  int id_;", "The motor number."],
        ["};", "End of the base class."],
        ["class ServoMotor : public Motor {", "ServoMotor IS-A Motor and adds servo features."],
        ["public:", "Public interface of the derived class."],
        ["  ServoMotor(int id, double gain) : Motor{id}, gain_{gain} {}", "Call the base constructor first, then set the extra member."],
        ["  double gain() const { return gain_; }", "A feature only servo motors have."],
        ["private:", "Hidden data."],
        ["  double gain_;", "Servo position gain."],
        ["};", "End of the derived class."],
      ),
      exercise:
        "Create Sensor as a base class (name, read()) and derive TemperatureSensor and EncoderSensor. Explain whether each relationship is is-a or has-a.",
    },
    {
      title: "Polymorphism and virtual functions",
      detail: "Calling the right function through a base pointer, override and virtual destructors.",
      time: "60–90 min",
      concept: [
        "A virtual function is chosen at run time from the real type of the object. Calling through a Base& or a Base* runs the derived override. Mark overrides with override so the compiler checks the signature matches.",
        "A base class that is deleted through a base pointer must have a virtual destructor, otherwise the derived part is never cleaned up. This is the rule behind every interface class in ROS 2.",
      ],
      example: cpp(
        ["class Controller {", "Base class that defines what every controller can do."],
        ["public:", "Public interface."],
        ["  virtual ~Controller() = default;", "Virtual destructor: deleting through a Controller pointer destroys the derived object properly."],
        ["  virtual double update(double error) { return 0.0; }", "A virtual function that derived classes may replace."],
        ["};", "End of the base class."],
        ["class PController : public Controller {", "A proportional controller."],
        ["public:", "Public interface."],
        ["  explicit PController(double kp) : kp_{kp} {}", "Store the gain."],
        ["  double update(double error) override { return kp_ * error; }", "override makes the compiler verify this really replaces the base function."],
        ["private:", "Hidden data."],
        ["  double kp_;", "Proportional gain."],
        ["};", "End of the derived class."],
        ["void run(Controller& c) { std::cout << c.update(2.0) << '\\n'; }", "Accepts any controller; the right update() is chosen at run time."],
      ),
      exercise:
        "Add a PIController next to PController. Write run() that takes Controller& and call it with both. Then remove virtual from the base update() and describe what changes.",
    },
    {
      title: "Abstract classes and interfaces",
      detail: "Pure virtual functions, interface classes, and swapping real hardware for a fake.",
      time: "45–75 min",
      concept: [
        "A pure virtual function (= 0) has no body and makes its class abstract: you cannot create an object of it, only of a derived class that provides every pure function. An abstract class with no data is an interface.",
        "Interfaces let application code depend on what a device does rather than which device it is. A test can pass a fake motor and the real program can pass hardware, without changing the application.",
      ],
      example: cpp(
        ["class MotorPort {", "An interface: what the application needs from a motor."],
        ["public:", "Public interface."],
        ["  virtual ~MotorPort() = default;", "Virtual destructor for safe deletion through the interface."],
        ["  virtual bool command(double torque) = 0;", "Pure virtual: every implementation must provide it."],
        ["};", "End of the interface."],
        ["class FakeMotor : public MotorPort {", "A test double that needs no hardware."],
        ["public:", "Public interface."],
        ["  bool command(double torque) override { last_ = torque; return true; }", "Remember the command and report success."],
        ["  double last() const { return last_; }", "Let a test inspect what was commanded."],
        ["private:", "Hidden data."],
        ["  double last_{0.0};", "The most recent torque command."],
        ["};", "End of the fake."],
        ["// MotorPort port;", "Would not compile: an abstract class cannot be instantiated."],
      ),
      exercise:
        "Define a MotorPort and FakeMotor. Write an application function that takes MotorPort& and clamps torque to 5 N·m. Test it with FakeMotor and confirm the last command.",
    },
    {
      title: "Operator overloading",
      detail: "Giving your types +, ==, and << with clear, predictable meaning.",
      time: "45–75 min",
      concept: [
        "Operator overloading lets your own types use the built-in operators: a Vec2 can support +, a Pose can support ==, and any type can support << for printing. Overload only when the meaning is obvious and matches the built-in behaviour.",
        "Free functions are used for symmetric operators (a + b) and for << on streams. Make comparison operators const and return bool. Do not overload operators for surprising behaviour.",
      ],
      example: cpp(
        ["struct Vec2 {", "A small 2D vector."],
        ["  double x{0.0}, y{0.0};", "Its two components."],
        ["};", "End of the struct."],
        ["Vec2 operator+(const Vec2& a, const Vec2& b) {", "Defines what a + b means for two Vec2 values."],
        ["  return Vec2{a.x + b.x, a.y + b.y};", "Add component by component and return the result."],
        ["}", "End of operator+."],
        ["bool operator==(const Vec2& a, const Vec2& b) {", "Defines equality."],
        ["  return a.x == b.x && a.y == b.y;", "Equal only when both components match exactly."],
        ["}", "End of operator==."],
        ["std::ostream& operator<<(std::ostream& out, const Vec2& v) {", "Lets std::cout print a Vec2."],
        ["  return out << '(' << v.x << \", \" << v.y << ')';", "Write the text and return the stream so calls can chain."],
        ["}", "End of operator<<."],
      ),
      exercise:
        "Add operator-, operator* by a double, and operator!= to Vec2. Print the sum of two vectors with std::cout, and write tests for each operator.",
    },
    {
      title: "Namespaces",
      detail: "Avoiding name clashes, using declarations, and the ROS 2 naming style.",
      time: "30–45 min",
      concept: [
        "A namespace groups names so that two libraries can each have a function called update without clashing. std is the standard library namespace and rclcpp is ROS 2's. Refer to a name with :: as in robot::Motor.",
        "Never write using namespace std; in a header, because it forces every includer to accept every name. A using declaration for one name inside a function is fine. Anonymous namespaces keep helpers private to one .cpp file.",
      ],
      example: cpp(
        ["namespace robot {", "Open the robot namespace; everything inside belongs to it."],
        ["struct Motor { int id{0}; };", "The full name of this type is robot::Motor."],
        ["namespace detail {", "A nested namespace for internal helpers."],
        ["inline int next_id() { static int n = 0; return ++n; }", "A helper users should not call directly."],
        ["}  // namespace detail", "Close the nested namespace."],
        ["}  // namespace robot", "Close the outer namespace."],
        ["robot::Motor m;", "Use the qualified name from outside."],
        ["m.id = robot::detail::next_id();", "Call the helper by its full name."],
        ["using robot::Motor;", "A using declaration brings in exactly one name."],
        ["namespace { int helper() { return 42; } }", "Anonymous namespace: helper is visible only inside this .cpp file."],
      ),
      exercise:
        "Put a Motor class in namespace robot::hardware and a Motor class in robot::sim. Use both in one main.cpp with qualified names, then explain why using namespace std; would be a bad idea in a header.",
    },
    {
      title: "Header files and project structure",
      detail: "Declarations in .hpp, definitions in .cpp, include guards and folder layout.",
      time: "45–75 min",
      concept: [
        "A header (.hpp) declares what a module offers; the source file (.cpp) defines how. Every .cpp that uses the module includes the header. Put #pragma once at the top of each header so it is only processed once per file.",
        "A common layout is include/<project>/ for public headers, src/ for sources and tests/ for tests. Include only what you use, and never define a non-inline function in a header, or the linker will report it twice.",
      ],
      example: sh(
        ["mkdir -p robot_lib/include/robot robot_lib/src robot_lib/tests", "Create the conventional folder layout in one command."],
        ["cat > robot_lib/include/robot/limits.hpp <<'EOF'", "Start writing the header file; the text up to the EOF line goes into it."],
        ["#pragma once", "Include the header only once per translation unit."],
        ["namespace robot { double clamp(double v, double low, double high); }", "Declare the function; no body here."],
        ["EOF", "End of the header."],
        ["cat > robot_lib/src/limits.cpp <<'EOF'", "Start writing the source file."],
        ["#include \"robot/limits.hpp\"", "Include our own header first, so a mismatch is caught by the compiler."],
        ["double robot::clamp(double v, double low, double high) { return v < low ? low : (v > high ? high : v); }", "Define the function declared in the header."],
        ["EOF", "End of the source file."],
        ["g++ -std=c++17 -Irobot_lib/include -c robot_lib/src/limits.cpp", "Compile it; -I adds the folder searched for #include lines."],
      ),
      exercise:
        "Split a Motor class into motor.hpp and motor.cpp, add #pragma once, and use it from main.cpp. Build with -I include, then deliberately define a function body in the header and include it from two .cpp files to see the linker error.",
    },
    {
      title: "Exceptions",
      detail: "try, catch, throw, exception types, and safe cleanup during unwinding.",
      time: "45–75 min",
      concept: [
        "An exception reports an error that the current function cannot handle. throw leaves the function immediately, destroys local objects (which is why RAII is important) and continues in the nearest matching catch. Throw objects derived from std::exception, such as std::runtime_error, and catch by const reference.",
        "Use exceptions for exceptional failures, such as a device missing at start-up, not for ordinary control flow. Mark functions that cannot fail noexcept; destructors are noexcept by default. ROS 2 code commonly catches exceptions at the node boundary.",
      ],
      example: cpp(
        ["#include <stdexcept>", "Header for std::runtime_error and friends."],
        ["double parse_speed(double raw) {", "A function that validates its input."],
        ["  if (raw < 0.0) throw std::invalid_argument(\"speed must be >= 0\");", "Report a programming/input error by throwing."],
        ["  return raw;", "Valid input passes through."],
        ["}", "End of parse_speed."],
        ["try {", "Code that may throw goes inside try."],
        ["  double s = parse_speed(-3.0);", "This throws, so the next lines are skipped."],
        ["  std::cout << s << '\\n';", "Not reached."],
        ["} catch (const std::invalid_argument& e) {", "Catch this specific error by const reference."],
        ["  std::cerr << \"error: \" << e.what() << '\\n';", "what() returns the message given to the exception."],
        ["}", "Execution continues here; local objects were cleaned up automatically."],
      ),
      exercise:
        "Write open_device(name) that throws std::runtime_error when name is empty. Call it inside try/catch, print e.what(), and show that a RAII object in the try block is destroyed during unwinding.",
    },
    {
      title: "Error handling patterns",
      detail: "Return codes, exceptions, std::optional results, and choosing between them.",
      time: "45–75 min",
      concept: [
        "There are three common patterns. Exceptions suit rare, serious failures. Return codes or bool suit hot paths and C-style APIs. std::optional<T> (C++17) or a small result struct suits 'the value might not exist' without any exception cost. Pick one pattern per layer and document it.",
        "Distinguish expected failures (a sensor read timed out) from programming errors (an index out of range). Handle the first, assert on the second. Never ignore an error result; the compiler can help with [[nodiscard]].",
      ],
      example: cpp(
        ["#include <optional>", "Header for std::optional (C++17)."],
        ["#include <string>", "Header for the error message type."],
        ["[[nodiscard]] std::optional<double> read_sensor(bool connected) {", "[[nodiscard]] warns if a caller ignores the result."],
        ["  if (!connected) return std::nullopt;", "No value: report 'nothing' instead of a fake number."],
        ["  return 21.5;", "A valid reading."],
        ["}", "End of read_sensor."],
        ["struct Result { bool ok; std::string message; };", "A tiny result type when you need a reason for failure."],
        ["Result start(bool port_free) {", "A function that reports why it failed."],
        ["  if (!port_free) return {false, \"port busy\"};", "Failure with an explanation."],
        ["  return {true, \"\"};", "Success, no message."],
        ["}", "End of start."],
        ["if (auto v = read_sensor(true)) std::cout << *v << '\\n';", "Test the optional, then use * to read the value inside."],
      ),
      exercise:
        "Implement one function three ways: throwing an exception, returning bool plus an out-parameter, and returning std::optional. Write a short note on which one you would use in a 1 kHz loop and which at start-up.",
    },
  ],
};
