import { cpp, sh, type CppPhase } from "./types";

export const phase1: CppPhase = {
  number: 1,
  title: "Phase 1 — C++ Foundations",
  blurb: "Everything you must know before touching ROS 2: the toolchain, the core language, memory and RAII.",
  lessons: [
    {
      title: "Compilers & the build process",
      detail: "GCC, Clang and MSVC; what happens between source code and a running program.",
      time: "45–75 min",
      concept: [
        "C++ source code is not run directly. A compiler translates it to machine code. GCC (g++) and Clang (clang++) are the usual compilers on Ubuntu and are what ROS 2 uses; MSVC is Microsoft's compiler on Windows. They accept the same language, but their warnings and error messages differ, so it helps to try both.",
        "This course uses C++17. Always tell the compiler the standard with -std=c++17 and turn warnings on with -Wall -Wextra -Wpedantic. Warnings are early feedback: fix them from the first build.",
      ],
      example: sh(
        ["g++ --version", "Print the GCC version; C++17 needs GCC 7 or newer."],
        ["clang++ --version", "Print the Clang version (optional; install with sudo apt install clang)."],
        ["g++ -std=c++17 -Wall -Wextra -Wpedantic main.cpp -o robot_app", "Compile main.cpp as C++17 with extra warnings; -o names the executable robot_app."],
        ["clang++ -std=c++17 -Wall -Wextra main.cpp -o robot_app_clang", "Build the same file with Clang and compare its messages with GCC's."],
        ["./robot_app", "Run the program you built from the current folder (./ means 'this folder')."],
        ["echo $?", "Print the exit code of the last command; 0 means the program reported success."],
      ),
      exercise:
        "Write a main.cpp that prints one line. Build it with g++ and with clang++ (if installed) using -std=c++17 -Wall -Wextra -Wpedantic. Add an unused variable, read the warning from each compiler, then remove it.",
    },
    {
      title: "Compilation vs linking; object files and executables",
      detail: "The four stages, .o object files, and why a missing definition is a linker error.",
      time: "45–75 min",
      concept: [
        "Building has stages: the preprocessor expands #include lines, the compiler turns each .cpp file into an object file (.o), and the linker joins object files and libraries into one executable. A compile error means one file is wrong; a link error means a piece is missing or defined twice.",
        "A function can be declared (its name and types are announced) in one file and defined (its body written) in another. If you call a function that was declared but never defined, the compiler is happy and the linker reports 'undefined reference'.",
      ],
      example: sh(
        ["g++ -std=c++17 -c main.cpp -o main.o", "Compile only (-c): turn main.cpp into the object file main.o without linking."],
        ["g++ -std=c++17 -c status.cpp -o status.o", "Compile the second source file into its own object file."],
        ["g++ main.o status.o -o robot_status", "Link both object files into the executable robot_status."],
        ["nm -C status.o | grep report", "List the symbols in status.o (-C demangles C++ names) and look for the function report."],
        ["ls -l main.o status.o robot_status", "Show the three build outputs and their sizes."],
      ),
      exercise:
        "Create main.cpp and status.cpp. Compile each with -c, then link. Next, misspell a function name in main.cpp and note the compiler error; then remove the body from status.cpp and note the linker error. Explain which stage reports each.",
    },
    {
      title: "Basic syntax, variables and types; auto basics",
      detail: "Statements, int/double/bool/char, const, initialization and auto.",
      time: "45–75 min",
      concept: [
        "A type tells the compiler what a value means and how much storage it needs: int for whole numbers, double for fractions, bool for true/false, char for one character. Use brace initialization ({}) because it refuses silent narrowing, such as squeezing a double into an int.",
        "auto lets the compiler deduce a variable's type from its initial value. Use it when the type is obvious or very long, but write the type yourself when it documents intent. Use const for any value that must not change.",
      ],
      example: cpp(
        ["const int encoder_ticks{2048};", "A read-only whole number: encoder counts for one full turn (brace initialization)."],
        ["const double radians{1.5708};", "A read-only fraction: a quarter turn in radians."],
        ["const auto ticks_per_radian = encoder_ticks / radians;", "auto deduces double, because int divided by double gives double."],
        ["bool moving{false};", "A true/false flag, starting as false."],
        ["char axis{'X'};", "A single character, written with single quotes."],
        ["// int bad{radians};", "Would not compile: braces refuse to squeeze a double into an int (this is the safety net)."],
      ),
      exercise:
        "Convert 2,048 encoder ticks per turn into ticks per degree using named const values. Print the result, then try int bad{1.5}; and read the error. Replace two obvious types with auto.",
    },
    {
      title: "Comments, formatting and naming",
      detail: "// and /* */ comments, readable layout, and naming conventions used in ROS 2.",
      time: "30–45 min",
      concept: [
        "A comment is text the compiler ignores. // comments to the end of the line; /* ... */ can span lines. Good comments explain why something is done, not what the syntax already says.",
        "Consistent formatting makes bugs visible. ROS 2 code uses snake_case for variables and functions, PascalCase for types, and a trailing underscore for member variables. Use a formatter such as clang-format so style is never a debate.",
      ],
      example: cpp(
        ["// Maximum joint speed the controller may command, in rad/s.", "A comment says why the number exists, not what the type is."],
        ["constexpr double max_joint_speed = 1.2;", "A compile-time constant in snake_case."],
        ["struct JointState {", "A type name in PascalCase."],
        ["  double position_rad{0.0};", "A member with its unit in the name so it cannot be misread."],
        ["};", "A struct ends with a semicolon."],
        ["/* A block comment can span several lines. */", "This form is useful for a longer explanation or to disable a block temporarily."],
      ),
      exercise:
        "Take a 15-line program you wrote earlier, rename every variable to snake_case with units where useful, add a why-comment for each constant, and run clang-format on it.",
    },
    {
      title: "Input and output: std::cout, std::cin, streams",
      detail: "Printing, reading numbers, checking that input succeeded, and string streams.",
      time: "45–75 min",
      concept: [
        "std::cout writes to standard output, std::cin reads from standard input, and std::cerr writes errors. The << operator sends values into a stream and >> extracts them. These are stream objects: the same operators also work on files and on std::stringstream.",
        "Input can fail, for example when the user types letters where a number is expected. Always check the stream (if (std::cin >> value)) before using the value.",
      ],
      example: cpp(
        ["#include <iostream>", "Header that provides std::cout, std::cin and std::cerr."],
        ["#include <sstream>", "Header for std::istringstream, a stream that reads from a string."],
        ["double target{};", "Variable to receive the target angle (value-initialized to 0.0)."],
        ["std::cout << \"Target angle (deg): \";", "Print a prompt without a newline."],
        ["if (!(std::cin >> target)) {", "Try to read a number; the condition is true when reading failed."],
        ["  std::cerr << \"not a number\\n\";", "Report the problem on the error stream."],
        ["  return 1;", "Leave main with a non-zero exit code, meaning failure."],
        ["}", "End of the failure branch."],
        ["std::istringstream line{\"12.5 3\"};", "A stream that reads from a string, handy for parsing and for tests."],
        ["int joint{}; double speed{}; line >> speed >> joint;", "Extract two values in order; a stream parses text into typed values."],
      ),
      exercise:
        "Read a joint number and an angle from std::cin. Reject a non-number without crashing, print the result with std::cout, then parse the same input from a std::istringstream in a test.",
    },
    {
      title: "Control flow: if, else and switch",
      detail: "Making decisions, comparing values, and the C++17 if-with-initializer.",
      time: "45–75 min",
      concept: [
        "if/else runs code only when a condition is true. switch chooses among several whole-number or enum values and should end each case with break. Prefer an enum class for states so a switch can list every case.",
        "C++17 lets an if declare a variable that only exists inside the if and its else: if (auto x = f(); x > 0). This keeps temporary values from leaking into the rest of the function.",
      ],
      example: cpp(
        ["enum class Mode { idle, moving, fault };", "A scoped enumeration: only three legal states and no accidental int conversions."],
        ["Mode mode{Mode::moving};", "Start in the moving state."],
        ["switch (mode) {", "Choose a branch based on the current mode."],
        ["  case Mode::idle: std::cout << \"waiting\\n\"; break;", "Idle: print and leave the switch (break stops fall-through)."],
        ["  case Mode::moving: std::cout << \"in motion\\n\"; break;", "Moving: print and leave the switch."],
        ["  case Mode::fault: std::cout << \"STOP\\n\"; break;", "Fault: print and leave the switch."],
        ["}", "End of the switch."],
        ["if (const double temp = read_temperature(); temp > 80.0) {", "C++17 initializer: temp exists only in this if/else and is tested at once."],
        ["  std::cout << \"too hot\\n\";", "Runs when the motor is above 80 degrees."],
        ["} else {", "Otherwise..."],
        ["  std::cout << \"ok\\n\";", "...the temperature is acceptable."],
        ["}", "End of the if/else."],
      ),
      exercise:
        "Model a gripper with an enum class State { open, closing, closed, fault } and a switch that prints the next allowed actions for each state. Add an if with initializer that reads a force value and enters fault above 40 N.",
    },
    {
      title: "Loops: for, while and do-while",
      detail: "Counting loops, range-based for, conditions, break and continue.",
      time: "45–75 min",
      concept: [
        "for repeats a counted block, while repeats as long as a condition holds, and do-while always runs at least once. Range-based for (for (const auto& x : items)) is the safest way to visit every element of a collection.",
        "Every loop needs a way to end. Check the condition, the update and the boundaries. An off-by-one error, such as <= size, reads one element past the end.",
      ],
      example: cpp(
        ["for (int joint = 0; joint < 6; ++joint) {", "Counted loop: joint takes the values 0 to 5 (< 6 stops before 6)."],
        ["  std::cout << \"joint \" << joint << '\\n';", "Print each joint number."],
        ["}", "End of the for loop."],
        ["double torque{0.0};", "Start with no torque."],
        ["while (torque < 5.0) {", "Repeat while the torque is below the 5 N·m limit."],
        ["  torque += 1.25;", "Raise the torque a step each time so the loop makes progress."],
        ["}", "End of the while loop; it ends after four steps."],
        ["int attempts{0};", "Count connection attempts."],
        ["do {", "Start a do-while: the body runs before the condition is checked."],
        ["  ++attempts;", "Count this attempt."],
        ["} while (attempts < 3 && !connect());", "Repeat while attempts remain and connecting failed; it always tries at least once."],
      ),
      exercise:
        "Print a table of 10 joint angles using for. Then write a while loop that ramps a velocity from 0 to a target in fixed steps, and a do-while that retries a simulated connection up to three times.",
    },
    {
      title: "Functions: parameters, return types and overloading",
      detail: "Declaring and calling functions, default arguments, and overloads by parameter type.",
      time: "45–75 min",
      concept: [
        "A function gives a piece of logic a name, typed inputs and an output. Pass small values (int, double) by value and larger objects by const reference (const std::string&). void means no return value.",
        "Overloading allows several functions with the same name if their parameter types differ. The compiler picks the best match at compile time. Default arguments let callers omit trailing parameters.",
      ],
      example: cpp(
        ["double clamp(double value, double low, double high) {", "Return type double; three double inputs passed by value."],
        ["  if (value < low) return low;", "Below the range: return the lower limit."],
        ["  if (value > high) return high;", "Above the range: return the upper limit."],
        ["  return value;", "Otherwise the value is already valid."],
        ["}", "End of clamp."],
        ["void print(int ticks) { std::cout << ticks << \" ticks\\n\"; }", "One overload of print, chosen when the argument is an int."],
        ["void print(double rad) { std::cout << rad << \" rad\\n\"; }", "A second overload, chosen when the argument is a double."],
        ["double move_by(double delta, double speed = 0.5);", "Declaration with a default: callers may omit speed and get 0.5."],
        ["print(2048);", "Calls the int overload."],
        ["print(1.57);", "Calls the double overload."],
      ),
      exercise:
        "Write clamp_velocity(requested, limit) that rejects a negative limit. Overload describe() for int and double, add a default argument, then test values below, inside and above the range.",
    },
    {
      title: "Arrays and strings: raw arrays, std::string, std::array",
      detail: "Fixed-size arrays, why raw arrays are risky, and safe alternatives.",
      time: "45–75 min",
      concept: [
        "A raw array (double angles[3]) is a fixed block with no size stored with it; it silently decays to a pointer when passed to a function, and going past the end is undefined behaviour. std::array<T, N> has the same fixed size but knows its size() and works with the standard algorithms.",
        "std::string owns and grows its text, and supports +, size() and comparison. Prefer std::string over char arrays. std::vector (Phase 3) is the resizable counterpart of std::array.",
      ],
      example: cpp(
        ["#include <array>", "Header for std::array."],
        ["#include <string>", "Header for std::string."],
        ["double raw[3] = {0.0, 0.5, -0.2};", "A raw array: three numbers, no bounds checking."],
        ["std::array<double, 3> joints{0.0, 0.5, -0.2};", "A safe fixed-size array that knows it holds 3 values."],
        ["joints.at(2) = 0.1;", "at() checks the index and throws if it is out of range."],
        ["std::string name{\"shoulder\"};", "A string that owns its characters."],
        ["name += \"_joint\";", "Append text; the string grows by itself."],
        ["std::cout << name << ' ' << name.size() << '\\n';", "Print the text and its length (14)."],
        ["for (double angle : joints) std::cout << angle << ' ';", "Range-based for visits each element."],
      ),
      exercise:
        "Store six joint names and six angles in two std::array objects, print each pair, and reject a sixth-plus-one access with at(). Explain in one sentence why the raw-array version would not catch the mistake.",
    },
    {
      title: "Pointers and references: T*, T& and passing by reference",
      detail: "Addresses, dereferencing, nullptr, references, and const references.",
      time: "60–90 min",
      concept: [
        "A pointer (T*) stores the address of a value and may be empty (nullptr). A reference (T&) is another name for an existing object and can never be empty or reseated. Use a reference for a required argument and a pointer only when absence is meaningful.",
        "Passing by value copies; passing by reference lets the function change the original; passing by const reference avoids a copy without allowing changes. Never dereference a pointer before checking it is not null.",
      ],
      example: cpp(
        ["void zero(double& value) { value = 0.0; }", "Takes a reference: writing to value changes the caller's variable."],
        ["double read_or(const double* sensor, double fallback) {", "Takes a pointer that may be null, promising not to modify what it points to."],
        ["  return sensor != nullptr ? *sensor : fallback;", "Dereference (*) only after the null check."],
        ["}", "End of read_or."],
        ["double joint{1.2};", "A normal variable."],
        ["zero(joint);", "joint is now 0.0, because the function received a reference."],
        ["double reading{3.4};", "A sensor value."],
        ["double a = read_or(&reading, -1.0);", "& takes the address of reading; the result is 3.4."],
        ["double b = read_or(nullptr, -1.0);", "No sensor: the fallback -1.0 is returned safely."],
      ),
      exercise:
        "Write swap_joints(double& a, double& b) and a function taking const std::vector<double>&. Then write one function that accepts a pointer and test both a valid pointer and nullptr.",
    },
    {
      title: "Memory model: stack vs heap, new/delete, and why raw pointers are dangerous",
      detail: "Where objects live, manual allocation, leaks and dangling pointers.",
      time: "60–90 min",
      concept: [
        "Local variables live on the stack and are destroyed automatically when the scope ends. Objects created with new live on the heap until you delete them. Forgetting delete leaks memory; deleting twice or using the object after delete is undefined behaviour.",
        "Raw owning pointers are dangerous because the type does not say who must delete the object, and any early return or exception skips the delete. Modern C++ therefore avoids new and delete in application code and uses RAII and smart pointers instead.",
      ],
      example: cpp(
        ["int on_stack{5};", "Lives on the stack; freed automatically at the closing brace."],
        ["int* on_heap = new int{5};", "Allocates an int on the heap and returns its address; you now own it."],
        ["std::cout << *on_heap << '\\n';", "Read through the pointer."],
        ["delete on_heap;", "Release the memory; the pointer now dangles."],
        ["on_heap = nullptr;", "Clear the pointer so it cannot be used by mistake."],
        ["double* buffer = new double[100];", "Allocates an array of 100 doubles on the heap."],
        ["delete[] buffer;", "Arrays need delete[]; plain delete on an array is undefined behaviour."],
        ["// std::vector<double> better(100);", "The safe alternative: memory is freed automatically."],
      ),
      exercise:
        "Write a function that allocates with new and returns early on an error path without deleting. Run it under g++ -fsanitize=address to see the leak report, then rewrite it with std::vector so the leak disappears.",
    },
    {
      title: "Structs and classes: members, methods and constructors",
      detail: "Bundling data and behaviour, public and private, constructors, const methods.",
      time: "60–90 min",
      concept: [
        "A struct or class groups related data (members) with the functions that operate on it (methods). In a struct everything is public by default; in a class everything is private by default. Keep data private so that no outside code can put an object into an invalid state.",
        "A constructor sets the starting state and can validate its arguments. Use the member initializer list (: id_{id}) to initialize members. Mark methods that do not change the object const.",
      ],
      example: cpp(
        ["class Motor {", "A new type that bundles motor data with its operations."],
        ["public:", "The functions below are the public interface."],
        ["  Motor(int id, double max_speed) : id_{id}, max_speed_{max_speed} {}", "Constructor: initializes both members using the initializer list."],
        ["  int id() const { return id_; }", "Getter; const promises it does not change the motor."],
        ["  bool set_speed(double speed) {", "A method that changes state, but only for legal values."],
        ["    if (speed < 0.0 || speed > max_speed_) return false;", "Reject speeds outside the allowed range."],
        ["    speed_ = speed;", "Store the accepted value."],
        ["    return true;", "Report success."],
        ["  }", "End of set_speed."],
        ["private:", "Data below is hidden from outside code."],
        ["  int id_;", "Motor number."],
        ["  double max_speed_;", "Configured upper limit."],
        ["  double speed_{0.0};", "Current speed, starting at zero."],
        ["};", "A class definition ends with a semicolon."],
      ),
      exercise:
        "Create a Motor class whose constructor requires an ID and a maximum speed. Add a const status() method returning a std::string and make set_speed refuse values outside the range. Test both cases.",
    },
    {
      title: "RAII: deterministic cleanup, and why ROS 2 uses it everywhere",
      detail: "Acquire in the constructor, release in the destructor, and stay leak-free.",
      time: "60–90 min",
      concept: [
        "RAII (Resource Acquisition Is Initialization) ties a resource to an object's lifetime: acquire it in the constructor and release it in the destructor. C++ guarantees the destructor runs when the object leaves scope, including on early return and exceptions, so cleanup is deterministic.",
        "ROS 2 relies on this everywhere: a node, publisher, subscription and timer are objects whose lifetime controls the connection to the middleware, and rclcpp::init/shutdown, locks and file handles follow the same rule. Learn the pattern here and the ROS 2 API will feel natural.",
      ],
      example: cpp(
        ["class MotorSession {", "A type whose lifetime means 'the motor connection is open'."],
        ["public:", "Members below are public."],
        ["  MotorSession() { std::cout << \"connect\\n\"; }", "Constructor: acquire the resource the moment the object exists."],
        ["  ~MotorSession() { std::cout << \"disconnect\\n\"; }", "Destructor: release it automatically when the object dies."],
        ["  MotorSession(const MotorSession&) = delete;", "Forbid copying so two objects cannot both close the same connection."],
        ["  MotorSession& operator=(const MotorSession&) = delete;", "Forbid copy assignment for the same reason."],
        ["};", "End of the class."],
        ["void run() {", "A function that uses the session."],
        ["  MotorSession session;", "Prints connect."],
        ["  if (!ready()) return;", "Early return: the destructor still runs and prints disconnect."],
        ["  std::cout << \"working\\n\";", "Normal work."],
        ["}", "session leaves scope here: disconnect is printed on every path."],
      ),
      exercise:
        "Implement DeviceSession that logs connect on construction and disconnect on destruction. Call it from a function with an early return and one that throws, and prove cleanup happens both times.",
    },
  ],
};
