import { cpp, sh, xml, type CppPhase } from "./types";

export const phase7: CppPhase = {
  number: 7,
  title: "Phase 7 — ROS 2 C++",
  blurb: "Where your C++ training meets robotics: nodes, topics, services, actions, TF2, URDF, Gazebo, Nav2 and lifecycle nodes.",
  lessons: [
    {
      title: "ROS 2 nodes in C++",
      detail: "rclcpp::init, rclcpp::Node, spin and shutdown.",
      time: "60–90 min",
      concept: [
        "A ROS 2 C++ node is a class derived from rclcpp::Node. main() calls rclcpp::init, creates the node with std::make_shared, runs rclcpp::spin (the event loop from Phase 6), and calls rclcpp::shutdown. The base class constructor takes the node's name.",
        "Source /opt/ros/lyrical/setup.bash first, and use RCLCPP_INFO(this->get_logger(), ...) for logging. Ctrl+C makes spin return so the destructors (RAII) run and shut everything down cleanly.",
      ],
      example: cpp(
        ["#include \"rclcpp/rclcpp.hpp\"", "The main rclcpp header: Node, init, spin, logging macros."],
        ["class HelloNode : public rclcpp::Node {", "Our node IS-A rclcpp::Node."],
        ["public:", "Public interface."],
        ["  HelloNode() : Node(\"hello_node\") {", "Call the base constructor with the node's name."],
        ["    RCLCPP_INFO(get_logger(), \"hello from C++17\");", "Log an info message through ROS 2's logger."],
        ["  }", "End of the constructor."],
        ["};", "End of the class."],
        ["int main(int argc, char** argv) {", "Program entry point; ROS reads its arguments from argc/argv."],
        ["  rclcpp::init(argc, argv);", "Initialize the ROS 2 client library."],
        ["  rclcpp::spin(std::make_shared<HelloNode>());", "Create the node and process its events until Ctrl+C."],
        ["  rclcpp::shutdown();", "Release ROS 2 resources."],
        ["  return 0;", "Exit with success."],
        ["}", "End of main."],
      ),
      exercise:
        "Create a package with ros2 pkg create --build-type ament_cmake, add HelloNode, build with colcon, run it with ros2 run, and confirm with ros2 node list from a second terminal. Press Ctrl+C and verify a clean exit.",
    },
    {
      title: "Publishers",
      detail: "create_publisher, message types, QoS depth and wall timers.",
      time: "60–90 min",
      concept: [
        "A publisher sends messages of one type to a named topic. create_publisher<MsgT>(topic, qos) returns a shared pointer that you keep as a member, so its lifetime equals the node's. std_msgs::msg::String is a simple standard message.",
        "A wall timer usually drives publishing: create_wall_timer(500ms, callback). The number in the QoS (10) is the queue depth. Check the result with ros2 topic echo and ros2 topic hz.",
      ],
      example: cpp(
        ["#include \"std_msgs/msg/string.hpp\"", "Generated C++ class for the String message."],
        ["using namespace std::chrono_literals;", "Enables the 500ms literal."],
        ["class Talker : public rclcpp::Node {", "A node that publishes."],
        ["public:", "Public interface."],
        ["  Talker() : Node(\"talker\") {", "Name the node."],
        ["    pub_ = create_publisher<std_msgs::msg::String>(\"chatter\", 10);", "Create a publisher on /chatter with queue depth 10."],
        ["    timer_ = create_wall_timer(500ms, [this] {", "Every 500 ms run this lambda."],
        ["      std_msgs::msg::String msg;", "Create an empty message."],
        ["      msg.data = \"count \" + std::to_string(++n_);", "Fill in its data field."],
        ["      pub_->publish(msg);", "Send it."],
        ["    });", "End of the lambda and timer."],
        ["  }", "End of the constructor."],
        ["private:", "Hidden state."],
        ["  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr pub_;", "Keep the publisher alive as long as the node."],
        ["  rclcpp::TimerBase::SharedPtr timer_; int n_{0};", "The timer and a counter."],
        ["};", "End of the class."],
      ),
      exercise:
        "Publish a sensor_msgs/msg/Temperature message at 2 Hz. Check the rate with ros2 topic hz, print one message with ros2 topic echo, then change the period to 100 ms and confirm the new rate.",
    },
    {
      title: "Subscribers",
      detail: "create_subscription, callback signatures, shared-pointer messages and QoS matching.",
      time: "60–90 min",
      concept: [
        "A subscriber receives every message published on a topic and calls your callback. The callback takes a const shared pointer to the message, so no copy is made. Publisher and subscriber must use compatible Quality of Service, otherwise no messages arrive.",
        "The callback runs on the executor thread, so it must be short (Phase 6). Store the data and let a timer or another thread do heavy work. Use ros2 topic info -v to check the QoS of each endpoint.",
      ],
      example: cpp(
        ["class Listener : public rclcpp::Node {", "A node that receives messages."],
        ["public:", "Public interface."],
        ["  Listener() : Node(\"listener\") {", "Name the node."],
        ["    sub_ = create_subscription<std_msgs::msg::String>(", "Create a subscription for String messages..."],
        ["      \"chatter\", 10,", "...on /chatter with queue depth 10..."],
        ["      [this](const std_msgs::msg::String::SharedPtr msg) {", "...and run this lambda for each message."],
        ["        RCLCPP_INFO(get_logger(), \"heard: %s\", msg->data.c_str());", "Log the text; %s needs a C string."],
        ["      });", "End of the lambda and the call."],
        ["  }", "End of the constructor."],
        ["private:", "Hidden state."],
        ["  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr sub_;", "Keep the subscription alive with the node."],
        ["};", "End of the class."],
      ),
      exercise:
        "Write a subscriber for the Talker's topic that counts messages and warns if none arrive for 2 seconds (use a timer). Test with the talker running, stopped and restarted.",
    },
    {
      title: "Services",
      detail: "Request and response calls with create_service and create_client.",
      time: "60–90 min",
      concept: [
        "A service is a short request and response, like a function call between nodes. The server registers a callback that fills in the response; the client sends a request and receives a future for the answer. Use it for quick queries and commands, such as 'reset the counter'.",
        "Do not call spin_until_future_complete inside a callback, and do not use a service for work that takes seconds; that is a job for an action. Check that the service is available with wait_for_service before calling.",
      ],
      example: cpp(
        ["#include \"example_interfaces/srv/add_two_ints.hpp\"", "A ready-made service type with a and b in the request, sum in the response."],
        ["class AddServer : public rclcpp::Node {", "The server node."],
        ["public:", "Public interface."],
        ["  AddServer() : Node(\"add_server\") {", "Name the node."],
        ["    srv_ = create_service<example_interfaces::srv::AddTwoInts>(\"add\",", "Offer a service named /add."],
        ["      [](const std::shared_ptr<example_interfaces::srv::AddTwoInts::Request> req,", "The callback receives the request..."],
        ["         std::shared_ptr<example_interfaces::srv::AddTwoInts::Response> res) {", "...and a response object to fill in."],
        ["        res->sum = req->a + req->b;", "Compute the answer."],
        ["      });", "End of the callback."],
        ["  }", "End of the constructor."],
        ["private:", "Hidden state."],
        ["  rclcpp::Service<example_interfaces::srv::AddTwoInts>::SharedPtr srv_;", "Keep the service alive with the node."],
        ["};", "End of the class."],
      ),
      exercise:
        "Implement the AddServer and a client that calls it with 2 and 3. Test with ros2 service call, then stop the server and confirm the client's wait_for_service times out instead of hanging forever.",
    },
    {
      title: "Actions",
      detail: "Goals with feedback, results and cancellation using rclcpp_action.",
      time: "90–120 min",
      concept: [
        "An action is for work that takes time: a client sends a goal, the server accepts it, sends periodic feedback, and finally returns a result. The client can cancel the goal at any time. Navigating to a pose and moving an arm are typical actions.",
        "An action server needs three callbacks: handle_goal (accept or reject), handle_cancel (accept a cancel request) and handle_accepted (start the work, usually on another thread so the executor is free). Test with ros2 action send_goal --feedback.",
      ],
      example: cpp(
        ["#include \"rclcpp_action/rclcpp_action.hpp\"", "Action server and client support for rclcpp."],
        ["#include \"example_interfaces/action/fibonacci.hpp\"", "A ready-made action type with a goal, feedback and result."],
        ["using Fib = example_interfaces::action::Fibonacci;", "A short name for the action type."],
        ["server_ = rclcpp_action::create_server<Fib>(this, \"fibonacci\",", "Create an action server named /fibonacci on this node."],
        ["  [](const rclcpp_action::GoalUUID&, std::shared_ptr<const Fib::Goal>) {", "handle_goal: called for every new goal."],
        ["    return rclcpp_action::GoalResponse::ACCEPT_AND_EXECUTE;", "Accept every goal (real code validates it)."],
        ["  },", "End of handle_goal."],
        ["  [](std::shared_ptr<rclcpp_action::ServerGoalHandle<Fib>>) {", "handle_cancel: called when a client cancels."],
        ["    return rclcpp_action::CancelResponse::ACCEPT;", "Allow cancellation."],
        ["  },", "End of handle_cancel."],
        ["  [this](std::shared_ptr<rclcpp_action::ServerGoalHandle<Fib>> h) {", "handle_accepted: start the work."],
        ["    std::thread{[h] { auto r = std::make_shared<Fib::Result>(); h->succeed(r); }}.detach();", "Run on a worker thread and report success (a real server sends feedback in a loop)."],
        ["  });", "End of handle_accepted and the call."],
      ),
      exercise:
        "Implement the Fibonacci action with feedback after each number and a cancel check inside the loop. Send a goal with ros2 action send_goal --feedback, then cancel it from a second terminal and confirm the server stops.",
    },
    {
      title: "Parameters",
      detail: "declare_parameter, get_parameter, defaults, and reacting to changes.",
      time: "60–90 min",
      concept: [
        "Parameters are named settings of a node, such as a rate or a limit. In C++ you must declare each one with declare_parameter(name, default) and then read it with get_parameter(name). The declared type is enforced.",
        "Parameters can be changed while the node runs with ros2 param set. Register a parameter callback to validate and apply changes, and return a failure for an invalid value. Collect them in the configuration struct from Phase 6.",
      ],
      example: cpp(
        ["class ArmNode : public rclcpp::Node {", "A node with settings."],
        ["public:", "Public interface."],
        ["  ArmNode() : Node(\"arm_node\") {", "Name the node."],
        ["    declare_parameter<double>(\"max_speed\", 1.2);", "Declare a double parameter with a default of 1.2."],
        ["    declare_parameter<std::string>(\"frame\", \"base_link\");", "Declare a string parameter."],
        ["    cfg_.max_speed = get_parameter(\"max_speed\").as_double();", "Read the current value into the config struct."],
        ["    handle_ = add_on_set_parameters_callback([](const std::vector<rclcpp::Parameter>& ps) {", "Validate changes made at run time."],
        ["      rcl_interfaces::msg::SetParametersResult r; r.successful = true;", "Start by accepting the change."],
        ["      for (const auto& p : ps) if (p.get_name() == \"max_speed\" && p.as_double() <= 0.0) r.successful = false;", "Reject a non-positive speed."],
        ["      return r;", "Return the verdict to ROS."],
        ["    });", "End of the callback."],
        ["  }", "End of the constructor."],
        ["private:", "Hidden state."],
        ["  struct { double max_speed{1.2}; } cfg_;", "A tiny config struct."],
        ["  rclcpp::node_interfaces::OnSetParametersCallbackHandle::SharedPtr handle_;", "Keeps the callback registered."],
        ["};", "End of the class."],
      ),
      exercise:
        "Add rate_hz and frame parameters with defaults. Change them with ros2 param set, try to set a negative rate and confirm it is rejected, and print the values with ros2 param list and get.",
    },
    {
      title: "Launch files",
      detail: "Starting several nodes with parameters and remappings from one Python launch file.",
      time: "45–75 min",
      concept: [
        "A launch file starts a whole system with one command: nodes, parameters, remappings and other launch files. ROS 2 launch files are usually written in Python (a function that returns a LaunchDescription), though XML and YAML also work.",
        "Install the launch folder from CMake with install(DIRECTORY launch DESTINATION share/${PROJECT_NAME}), rebuild, and start it with ros2 launch package_name file.launch.py. Use launch arguments for values that change between runs.",
      ],
      example: sh(
        ["from launch import LaunchDescription", "Import the class that holds the list of things to start."],
        ["from launch_ros.actions import Node", "Import the action that starts one ROS 2 node."],
        ["def generate_launch_description():", "The function ros2 launch looks for."],
        ["    talker = Node(package='robot_nodes', executable='talker', name='talker', parameters=[{'rate_hz': 5.0}])", "Start the talker with one parameter set."],
        ["    listener = Node(package='robot_nodes', executable='listener', remappings=[('chatter', 'robot/chatter')])", "Start the listener and rename its topic."],
        ["    return LaunchDescription([talker, listener])", "Hand ROS the list of nodes to start."],
      ),
      exercise:
        "Write bringup.launch.py that starts a talker and a listener, passes a rate parameter to the talker and remaps the topic for both. Install it, launch it, and check the graph with ros2 node list and ros2 topic list.",
    },
    {
      title: "TF2 transforms",
      detail: "Coordinate frames, broadcasting transforms and looking them up in C++.",
      time: "90–120 min",
      concept: [
        "A robot has many coordinate frames: base_link, each joint, the camera, the map. TF2 keeps them as a tree of transforms (translation plus rotation) that change over time. A transform broadcaster publishes 'child frame relative to parent frame' and a buffer plus listener lets any node ask for the transform between two frames.",
        "Frame names are strings, orientation is a quaternion, and lookups can fail if the transform is not available yet, so catch tf2::TransformException. Inspect the tree with ros2 run tf2_tools view_frames.",
      ],
      example: cpp(
        ["#include \"tf2_ros/transform_broadcaster.h\"", "Publishes transforms."],
        ["#include \"tf2_ros/transform_listener.h\"", "Receives transforms into a buffer."],
        ["#include \"tf2_ros/buffer.h\"", "Stores recent transforms."],
        ["geometry_msgs::msg::TransformStamped t;", "One transform with a timestamp."],
        ["t.header.stamp = now();", "Time the transform is valid for."],
        ["t.header.frame_id = \"base_link\";", "The parent frame."],
        ["t.child_frame_id = \"camera_link\";", "The child frame."],
        ["t.transform.translation.x = 0.10;", "The camera sits 10 cm in front of the base."],
        ["t.transform.rotation.w = 1.0;", "Identity quaternion: no rotation."],
        ["broadcaster_->sendTransform(t);", "Publish it to /tf."],
        ["try { auto tf = buffer_->lookupTransform(\"base_link\", \"camera_link\", tf2::TimePointZero); }", "Ask for the latest base-to-camera transform."],
        ["catch (const tf2::TransformException& e) { RCLCPP_WARN(get_logger(), \"%s\", e.what()); }", "Handle a missing transform without crashing."],
      ),
      exercise:
        "Broadcast base_link→camera_link at 10 Hz with a slowly rotating quaternion. Write a listener node that looks up the transform each second and prints x, y, z. Check the tree with view_frames.",
    },
    {
      title: "URDF and robot_state_publisher",
      detail: "Describing links and joints, and publishing the robot's transforms from joint states.",
      time: "90–120 min",
      concept: [
        "URDF is an XML description of a robot: links (rigid bodies with shape, mass and inertia) connected by joints (fixed, revolute, prismatic) with limits. robot_state_publisher reads the URDF and the /joint_states topic and publishes the TF frames for every link.",
        "Check a URDF with check_urdf, view it in RViz2, and move its joints with joint_state_publisher_gui. Keep the description in its own package, use xacro for repeated parts, and always include limits, inertia and collision shapes if you plan to simulate it.",
      ],
      example: xml(
        ["<robot name=\"mini_arm\">", "Root element naming the robot."],
        ["  <link name=\"base_link\"/>", "The fixed base of the arm."],
        ["  <link name=\"upper_arm\"/>", "A moving link."],
        ["  <joint name=\"shoulder\" type=\"revolute\">", "A joint that rotates within limits."],
        ["    <parent link=\"base_link\"/>", "The joint connects to the base..."],
        ["    <child link=\"upper_arm\"/>", "...and moves the upper arm."],
        ["    <axis xyz=\"0 0 1\"/>", "Rotate around the vertical Z axis."],
        ["    <limit lower=\"-1.57\" upper=\"1.57\" effort=\"10\" velocity=\"1.0\"/>", "Range in radians, max torque in N·m and max speed in rad/s."],
        ["  </joint>", "End of the joint."],
        ["</robot>", "End of the robot description."],
      ),
      exercise:
        "Extend mini_arm with an elbow joint and a forearm link, validate it with check_urdf, run robot_state_publisher with it, publish /joint_states with joint_state_publisher_gui, and watch the frames in RViz2.",
    },
    {
      title: "Gazebo simulation",
      detail: "Spawning a URDF in Gazebo, bridging topics and controlling a simulated robot.",
      time: "90–120 min",
      concept: [
        "Gazebo is a physics simulator: it loads a world, spawns your robot from its URDF/SDF and simulates gravity, contacts and sensors. The ros_gz bridge connects Gazebo topics to ROS 2 topics, so your nodes talk to a simulated robot exactly as they will to a real one.",
        "Use simulated time (use_sim_time:=true) so that ROS 2 nodes follow Gazebo's clock. Simulation is safe for testing controllers, but verify on hardware carefully because friction, latency and sensor noise are never perfect.",
      ],
      example: xml(
        ["ros2 launch ros_gz_sim gz_sim.launch.py gz_args:='-r empty.sdf'", "Start Gazebo with an empty world, running immediately (-r)."],
        ["ros2 run ros_gz_sim create -name mini_arm -topic robot_description", "Spawn the robot from the robot_description topic."],
        ["ros2 run ros_gz_bridge parameter_bridge /cmd_vel@geometry_msgs/msg/Twist]gz.msgs.Twist", "Bridge the ROS 2 /cmd_vel topic into Gazebo."],
        ["ros2 topic pub -r 10 /cmd_vel geometry_msgs/msg/Twist '{linear: {x: 0.2}}'", "Drive forward at 0.2 m/s, publishing at 10 Hz."],
        ["ros2 param set /my_node use_sim_time true", "Make a node follow simulated time."],
      ),
      exercise:
        "Spawn a differential-drive robot in Gazebo, bridge /cmd_vel and /odom, and write a C++ node that drives 1 metre forward and stops using the odometry. Record the actual distance and the overshoot.",
    },
    {
      title: "Navigation stack basics (Nav2)",
      detail: "Maps, localization, planners and controllers, and sending a NavigateToPose goal.",
      time: "90–120 min",
      concept: [
        "Nav2 is ROS 2's navigation framework. It needs a map, a localization source (AMCL or SLAM), a costmap of obstacles, a global planner (path from A to B), a local controller (follows the path and avoids obstacles) and behaviour-tree recovery actions. Everything is configured with parameters.",
        "Your code usually talks to Nav2 through the NavigateToPose action: send a goal pose in the map frame and wait for the result. Start with the Nav2 TurtleBot demo in simulation, and check the TF tree first (map → odom → base_link).",
      ],
      example: cpp(
        ["#include \"nav2_msgs/action/navigate_to_pose.hpp\"", "The action type Nav2 exposes."],
        ["using Nav = nav2_msgs::action::NavigateToPose;", "A short name for it."],
        ["auto client = rclcpp_action::create_client<Nav>(node, \"navigate_to_pose\");", "Create an action client for the Nav2 server."],
        ["if (!client->wait_for_action_server(std::chrono::seconds(5))) return;", "Give up if Nav2 is not running."],
        ["Nav::Goal goal;", "The goal message."],
        ["goal.pose.header.frame_id = \"map\";", "Express the pose in the map frame."],
        ["goal.pose.pose.position.x = 2.0;", "Two metres along the map's X axis."],
        ["goal.pose.pose.orientation.w = 1.0;", "Face along X (identity quaternion)."],
        ["auto future = client->async_send_goal(goal);", "Send the goal; the future completes when the server answers."],
      ),
      exercise:
        "Start the Nav2 simulation demo, send a goal from RViz2, then write a C++ client that sends three goals in sequence and prints the result of each. Cancel one goal halfway and confirm the robot stops.",
    },
    {
      title: "Writing your own ROS 2 packages",
      detail: "package.xml, CMakeLists.txt with ament_cmake, installing targets and testing.",
      time: "90–120 min",
      concept: [
        "A ROS 2 C++ package is a folder with package.xml (name, version, dependencies, license) and CMakeLists.txt using ament_cmake. Dependencies are declared twice: in package.xml so colcon can order the build, and in CMake with find_package.",
        "The rules: link with ament_target_dependencies (or target_link_libraries with imported targets), install executables to lib/${PROJECT_NAME}, install launch and config folders to share/${PROJECT_NAME}, and end with ament_package(). Add tests with ament_add_gtest and run colcon test.",
      ],
      example: xml(
        ["cmake_minimum_required(VERSION 3.16)", "Required CMake version."],
        ["project(robot_nodes)", "Package name; must match package.xml."],
        ["set(CMAKE_CXX_STANDARD 17)", "This course uses C++17."],
        ["find_package(ament_cmake REQUIRED)", "The ROS 2 build helpers."],
        ["find_package(rclcpp REQUIRED)", "The C++ client library."],
        ["find_package(std_msgs REQUIRED)", "The message package we use."],
        ["add_executable(talker src/talker.cpp)", "Build the talker executable."],
        ["ament_target_dependencies(talker rclcpp std_msgs)", "Add include paths and libraries of the dependencies."],
        ["install(TARGETS talker DESTINATION lib/${PROJECT_NAME})", "Install where ros2 run looks for executables."],
        ["install(DIRECTORY launch config DESTINATION share/${PROJECT_NAME})", "Install launch files and configuration."],
        ["ament_package()", "Must be the last line; exports the package to ROS 2."],
      ),
      exercise:
        "Create robot_nodes with a talker and a listener, matching package.xml dependencies, a launch file and one gtest. Build with colcon build --symlink-install, source install/setup.bash, run colcon test, and check with ros2 pkg executables.",
    },
    {
      title: "Multi-threaded executors and callback groups",
      detail: "SingleThreadedExecutor vs MultiThreadedExecutor and avoiding blocked callbacks.",
      time: "90–120 min",
      concept: [
        "An executor takes ready callbacks (messages, timers, service requests) and runs them. rclcpp::spin uses a single-threaded executor: callbacks run one at a time. A MultiThreadedExecutor uses a pool of threads so callbacks can run in parallel, but only callbacks in different callback groups, or in a Reentrant group, may overlap.",
        "A MutuallyExclusive group (the default) never runs two of its callbacks together, so it is safe but serial. Use several groups when one callback blocks, such as a service client waiting for a response, and protect shared data with a mutex. Measure before adding threads.",
      ],
      example: cpp(
        ["auto node = std::make_shared<ArmNode>();", "Create the node."],
        ["rclcpp::executors::MultiThreadedExecutor exec{rclcpp::ExecutorOptions(), 4};", "An executor with a pool of four threads."],
        ["exec.add_node(node);", "Let the executor run the node's callbacks."],
        ["exec.spin();", "Run until shutdown; callbacks may now run in parallel."],
        ["auto fast = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);", "Group for callbacks that must not overlap each other."],
        ["auto slow = create_callback_group(rclcpp::CallbackGroupType::Reentrant);", "Group whose callbacks may run in parallel."],
        ["rclcpp::SubscriptionOptions opts; opts.callback_group = fast;", "Choose the group for a subscription."],
        ["sub_ = create_subscription<std_msgs::msg::String>(\"chatter\", 10, cb, opts);", "The subscription's callback now belongs to the fast group."],
      ),
      exercise:
        "Write a node with a timer whose callback sleeps 500 ms and a second 10 ms timer. Run them with a single-threaded executor and note the delay, then put them in different callback groups on a MultiThreadedExecutor and measure again.",
    },
    {
      title: "Lifecycle nodes",
      detail: "Managed states: unconfigured, inactive, active, and the transition callbacks.",
      time: "90–120 min",
      concept: [
        "A lifecycle (managed) node has a defined state machine: unconfigured, inactive, active and finalized. You build it from rclcpp_lifecycle::LifecycleNode and implement transition callbacks: on_configure (allocate resources), on_activate (start publishing), on_deactivate, on_cleanup and on_shutdown, each returning SUCCESS, FAILURE or ERROR.",
        "This gives a system a controlled start-up and shutdown: hardware is opened during configure and only starts moving on activate, and it can be paused without destroying the node. Drive it with ros2 lifecycle set /node configure and ros2 lifecycle get.",
      ],
      example: cpp(
        ["#include \"rclcpp_lifecycle/lifecycle_node.hpp\"", "Header for the lifecycle node base class."],
        ["using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;", "A short name for the return type of the transition callbacks."],
        ["class Driver : public rclcpp_lifecycle::LifecycleNode {", "A managed node."],
        ["public:", "Public interface."],
        ["  Driver() : LifecycleNode(\"driver\") {}", "Start in the unconfigured state."],
        ["  CallbackReturn on_configure(const rclcpp_lifecycle::State&) override {", "Called on the configure transition."],
        ["    pub_ = create_publisher<std_msgs::msg::String>(\"status\", 10);", "Create resources but do not use them yet."],
        ["    return CallbackReturn::SUCCESS;", "Move to the inactive state."],
        ["  }", "End of on_configure."],
        ["  CallbackReturn on_activate(const rclcpp_lifecycle::State&) override {", "Called on activate."],
        ["    pub_->on_activate();", "Lifecycle publishers only send once activated."],
        ["    return CallbackReturn::SUCCESS;", "Move to the active state."],
        ["  }", "End of on_activate."],
        ["private:", "Hidden state."],
        ["  rclcpp_lifecycle::LifecyclePublisher<std_msgs::msg::String>::SharedPtr pub_;", "A publisher that obeys the lifecycle."],
        ["};", "End of the class."],
      ),
      exercise:
        "Turn the Talker into a lifecycle node. Use ros2 lifecycle set to configure, activate, deactivate and clean it up, and confirm with ros2 topic echo that messages flow only while it is active.",
    },
  ],
};
