import { cpp, type CppPhase } from "./types";

export const phase3: CppPhase = {
  number: 3,
  title: "Phase 3 — Modern C++ (C++11–17)",
  blurb: "The heart of ROS 2 C++: smart pointers, move semantics, lambdas, the STL, threads and the C++17 vocabulary types.",
  lessons: [
    {
      title: "auto and type inference",
      detail: "How the compiler deduces types, auto with references and const, and structured bindings.",
      time: "45–60 min",
      concept: [
        "auto deduces a variable's type from its initializer, and the deduced type drops references and top-level const unless you write them: const auto& keeps a read-only reference and avoids a copy. decltype(expr) gives the exact type of an expression.",
        "C++17 adds structured bindings, which unpack a pair, tuple, array or simple struct into named variables. They make loops over maps much easier to read. ROS 2 code uses auto heavily for long types such as shared pointers.",
      ],
      example: cpp(
        ["#include <map>", "Header for std::map."],
        ["#include <string>", "Header for std::string."],
        ["auto count = 3;", "Deduced as int."],
        ["auto gain = 0.75;", "Deduced as double."],
        ["const auto& name = std::string{\"shoulder\"};", "const auto& binds a read-only reference; no copy is made."],
        ["std::map<std::string, double> limits{{\"shoulder\", 1.5}, {\"elbow\", 2.0}};", "A map from joint name to its limit."],
        ["for (const auto& [joint, limit] : limits) {", "Structured binding: unpack each key/value pair into joint and limit."],
        ["  std::cout << joint << \" \" << limit << '\\n';", "Print each pair."],
        ["}", "End of the loop."],
        ["decltype(gain) other = 1.5;", "decltype copies the exact type of gain (double)."],
      ),
      exercise:
        "Rewrite a loop over std::map<std::string, double> with structured bindings and const auto&. Then use decltype to declare a variable with the same type as an existing expression, and explain what auto would have dropped.",
    },
    {
      title: "Smart pointers: std::unique_ptr",
      detail: "Exclusive ownership, make_unique, transferring ownership and returning from functions.",
      time: "45–75 min",
      concept: [
        "std::unique_ptr<T> owns exactly one object and deletes it when the pointer is destroyed. It cannot be copied, only moved, so ownership is always clear. Create it with std::make_unique<T>(args...), never with new.",
        "Default to unique_ptr for anything on the heap. Pass a raw pointer or reference to a function that only uses the object, and pass the unique_ptr by value (with std::move) only to give ownership away.",
      ],
      example: cpp(
        ["#include <memory>", "Header for unique_ptr, shared_ptr and weak_ptr."],
        ["struct MotorDriver { void start() {} };", "A stand-in driver class."],
        ["auto driver = std::make_unique<MotorDriver>();", "Create the driver on the heap with one owner; no new or delete."],
        ["driver->start();", "-> reaches the object, exactly like a raw pointer."],
        ["auto other = std::move(driver);", "Transfer ownership; driver is now empty (nullptr)."],
        ["if (!driver) std::cout << \"moved out\\n\";", "A moved-from unique_ptr tests false."],
        ["std::unique_ptr<MotorDriver> make() { return std::make_unique<MotorDriver>(); }", "A factory that returns ownership to the caller."],
        ["auto fresh = make();", "The returned pointer is moved into fresh automatically."],
        ["// other and fresh are deleted automatically at the end of the scope.", "No delete anywhere: RAII does the cleanup."],
      ),
      exercise:
        "Write a factory returning std::unique_ptr<MotorPort>. Store two in a vector, transfer one to another owner with std::move, and prove each is destroyed exactly once by logging in the destructor.",
    },
    {
      title: "Smart pointers: std::shared_ptr and std::weak_ptr",
      detail: "Shared ownership, reference counts, weak observers and breaking cycles.",
      time: "60–90 min",
      concept: [
        "std::shared_ptr<T> lets several owners share an object; it is deleted when the last owner is gone (a reference count). std::weak_ptr observes without owning, and lock() gives a shared_ptr if the object is still alive. Create shared pointers with std::make_shared.",
        "ROS 2 hands you shared pointers everywhere: nodes, messages and publishers. Use weak_ptr for back-references such as a child pointing to its parent; two shared_ptrs pointing at each other form a cycle and never free.",
      ],
      example: cpp(
        ["#include <memory>", "Header for the smart pointers."],
        ["struct Status { int fault{0}; };", "Shared status data."],
        ["auto status = std::make_shared<Status>();", "Create a shared object; the count is 1."],
        ["auto viewer = status;", "Copying a shared_ptr adds an owner; the count is 2."],
        ["std::cout << status.use_count() << '\\n';", "Print the number of owners (2)."],
        ["std::weak_ptr<Status> watcher = status;", "A weak observer: does not change the count."],
        ["status.reset(); viewer.reset();", "Both owners let go, so the Status is destroyed."],
        ["if (auto alive = watcher.lock()) {", "lock() returns a shared_ptr only if the object still exists."],
        ["  std::cout << alive->fault << '\\n';", "Not reached here: the object is gone."],
        ["} else { std::cout << \"expired\\n\"; }", "The weak_ptr correctly reports that it expired."],
      ),
      exercise:
        "Build a Parent that owns Children with shared_ptr where each Child holds a weak_ptr back to the Parent. Log destructors and confirm everything is freed. Then change the back-pointer to shared_ptr and observe the leak.",
    },
    {
      title: "Move semantics: move constructor, move assignment and std::move",
      detail: "Transferring resources instead of copying, and the rule of five.",
      time: "60–90 min",
      concept: [
        "Copying duplicates a resource; moving transfers it from an object that is about to be discarded. A move constructor (T(T&&)) and move assignment (T& operator=(T&&)) steal the buffer and leave the source valid but empty. std::move does not move anything: it only marks an object as movable.",
        "If a class manages a resource, define or delete all five special functions (destructor, copy constructor, copy assignment, move constructor, move assignment). Mark moves noexcept so containers use them. Do not use a moved-from object except to assign or destroy it.",
      ],
      example: cpp(
        ["class Frame {", "A type that owns a growable buffer."],
        ["public:", "Public interface."],
        ["  explicit Frame(std::size_t n) : data_(n) {}", "Allocate n values."],
        ["  Frame(const Frame&) = default;", "Copy constructor: duplicate the buffer."],
        ["  Frame& operator=(const Frame&) = default;", "Copy assignment: overwrite with a duplicate."],
        ["  Frame(Frame&& other) noexcept : data_{std::move(other.data_)} {}", "Move constructor: steal the buffer; noexcept lets vectors use it."],
        ["  Frame& operator=(Frame&& other) noexcept { data_ = std::move(other.data_); return *this; }", "Move assignment: steal the buffer from other."],
        ["  ~Frame() = default;", "The vector member frees itself."],
        ["private:", "Hidden data."],
        ["  std::vector<double> data_;", "The owned resource."],
        ["};", "End of the class."],
        ["Frame a{1000};", "Create a frame with 1000 values."],
        ["Frame b = std::move(a);", "Move: b takes the buffer; a is valid but empty."],
      ),
      exercise:
        "Create a FrameBuffer that logs 'copy' and 'move' from its special functions. Return one from a function, put it in a vector, and compare the log with and without std::move at the call site.",
    },
    {
      title: "Lambdas: capture lists and inline callbacks",
      detail: "Anonymous functions, [=] vs [&] vs explicit captures, and lambdas as callbacks.",
      time: "60–90 min",
      concept: [
        "A lambda is an unnamed function written where it is used: [captures](parameters) { body }. The capture list chooses which outside variables the lambda can use: [x] copies x, [&x] refers to x, [this] captures the current object, and [=] or [&] capture everything used. Prefer explicit captures.",
        "Lambdas are how ROS 2 callbacks are written: a subscription or timer takes a lambda that runs when data arrives. A lambda that captures a reference must not outlive that variable, or it will read freed memory.",
      ],
      example: cpp(
        ["int threshold = 80;", "A local variable the lambda will use."],
        ["auto too_hot = [threshold](double temp) { return temp > threshold; };", "Capture threshold by copy and return whether temp exceeds it."],
        ["std::cout << too_hot(85.0) << '\\n';", "Call the lambda like a function; prints 1 (true)."],
        ["int count = 0;", "A counter the lambda will change."],
        ["auto on_message = [&count](const std::string& text) {", "Capture count by reference so the lambda can modify it."],
        ["  ++count;", "Runs each time the callback is invoked."],
        ["  std::cout << text << '\\n';", "Show the message."],
        ["};", "End of the lambda."],
        ["on_message(\"hello\");", "First call: count becomes 1."],
        ["on_message(\"again\");", "Second call: count becomes 2."],
      ),
      exercise:
        "Write a function register_callback(std::function<void(int)>) that stores a callback. Register a lambda capturing a counter by reference, call it three times, then explain why capturing a local by reference would be dangerous if the callback ran after the function returned.",
    },
    {
      title: "STL containers: vector, map, unordered_map, list",
      detail: "Choosing between the standard containers and their costs.",
      time: "60–90 min",
      concept: [
        "std::vector is a resizable contiguous array and should be your default. std::map keeps keys sorted (O(log n) lookup), std::unordered_map hashes keys (average O(1) lookup, no order), and std::list is a doubly linked list that is rarely the best choice because it is slow to traverse.",
        "Pick a container from how you use it. Call reserve() on a vector when you know the size, remember that push_back may reallocate (invalidating references), and prefer emplace_back to construct in place.",
      ],
      example: cpp(
        ["#include <vector>", "Resizable contiguous array."],
        ["#include <map>", "Sorted key-value container."],
        ["#include <unordered_map>", "Hash-based key-value container."],
        ["#include <list>", "Doubly linked list."],
        ["std::vector<double> angles;", "An empty list of angles."],
        ["angles.reserve(6);", "Allocate room for six values once, avoiding reallocations."],
        ["angles.push_back(0.5);", "Append a value at the end."],
        ["std::map<std::string, int> ids{{\"elbow\", 2}, {\"base\", 1}};", "A sorted map; iterating it visits 'base' before 'elbow'."],
        ["std::unordered_map<std::string, double> temps;", "A hash map for fast lookup by name."],
        ["temps[\"motor1\"] = 41.5;", "Insert or update a key with operator[]."],
        ["if (auto it = temps.find(\"motor2\"); it == temps.end()) std::cout << \"missing\\n\";", "find returns end() when the key is absent."],
        ["std::list<int> queue{1, 2, 3};", "A linked list; use only when you really need cheap insertion in the middle."],
      ),
      exercise:
        "Store 1,000 motor temperatures in a vector with reserve, index them by name in an unordered_map, and compare timings for lookup in a vector, map and unordered_map. Explain the results.",
    },
    {
      title: "STL algorithms: sort, find and for_each",
      detail: "Expressing intent with <algorithm> instead of hand-written loops.",
      time: "45–75 min",
      concept: [
        "The standard algorithms operate on iterator ranges [begin, end): the first position is included and the end position is one past the last element. sort orders a range, find_if locates the first match, for_each applies an action, and accumulate (in <numeric>) sums a range.",
        "Algorithms take lambdas as the rule to apply. They are shorter, harder to get wrong than a raw index loop, and tell the reader what you mean. Sort a copy if the original order matters.",
      ],
      example: cpp(
        ["#include <algorithm>", "Header for sort, find_if, for_each and friends."],
        ["#include <numeric>", "Header for accumulate."],
        ["std::vector<double> temps{41.0, 85.5, 62.0, 90.1};", "Sample motor temperatures."],
        ["auto sorted = temps;", "Copy so the original order stays unchanged."],
        ["std::sort(sorted.begin(), sorted.end());", "Order the copy from smallest to largest."],
        ["auto hot = std::find_if(temps.begin(), temps.end(),", "Search for the first element matching the rule on the next line."],
        ["  [](double t) { return t > 80.0; });", "The rule: temperature above 80. hot equals end() if nothing matches."],
        ["std::for_each(temps.begin(), temps.end(), [](double t) { std::cout << t << ' '; });", "Apply a printing lambda to every element."],
        ["double sum = std::accumulate(temps.begin(), temps.end(), 0.0);", "Add all values, starting from 0.0 (a double, so the sum is a double)."],
      ),
      exercise:
        "Given ten temperature samples, sort a copy, find the first value above 80 °C, count the values above 60 with std::count_if, and compute the mean with accumulate. Confirm that the original order is unchanged.",
    },
    {
      title: "Iterators: input, output, forward, bidirectional and random-access",
      detail: "The five iterator categories and what each one allows.",
      time: "45–75 min",
      concept: [
        "An iterator is an object that points into a container and moves through it. begin() points to the first element and end() one past the last. Dereferencing (*it) reads the element and ++it moves to the next.",
        "There are five categories, each adding abilities: input (read once, forward), output (write once, forward), forward (multi-pass), bidirectional (also --it, e.g. std::list and std::map) and random-access (also it + n and it2 - it1, e.g. std::vector and std::array). An algorithm states the category it needs; std::sort needs random access, so it does not work on a std::list.",
      ],
      example: cpp(
        ["std::vector<int> v{10, 20, 30, 40};", "A vector supplies random-access iterators."],
        ["auto it = v.begin();", "it points at the first element (10)."],
        ["it += 2;", "Random access: jump two elements ahead in one step."],
        ["std::cout << *it << '\\n';", "Dereference: prints 30."],
        ["std::cout << (v.end() - v.begin()) << '\\n';", "Random-access iterators can be subtracted: prints 4, the size."],
        ["std::list<int> l{1, 2, 3};", "A list supplies only bidirectional iterators."],
        ["auto last = std::prev(l.end());", "prev steps backwards from end() to the final element."],
        ["std::cout << *last << '\\n';", "Prints 3."],
        ["// l.begin() + 2;", "Would not compile: bidirectional iterators cannot jump."],
      ),
      exercise:
        "Write a function that prints any container with begin()/end(), then try std::sort on a std::vector and a std::list. Read the error for the list and name the missing iterator ability.",
    },
    {
      title: "std::chrono: timing and durations",
      detail: "Clocks, time points, durations, and typed time literals.",
      time: "45–60 min",
      concept: [
        "std::chrono separates three ideas: a clock (steady_clock never jumps backwards, system_clock follows the wall clock), a time_point (a moment) and a duration (a length of time) with a unit. Durations are typed, so mixing seconds and milliseconds is safe and converts correctly.",
        "Use steady_clock for measuring intervals and deadlines. Convert only at the edges with duration_cast. The literals 1ms, 250us and 2s come from std::chrono_literals. ROS 2 timers and rates take std::chrono durations directly.",
      ],
      example: cpp(
        ["#include <chrono>", "Header for clocks, time points and durations."],
        ["using namespace std::chrono_literals;", "Enable the 10ms / 2s literal suffixes."],
        ["const auto start = std::chrono::steady_clock::now();", "Record the current moment on a monotonic clock."],
        ["run_step();", "The work being timed."],
        ["const auto elapsed = std::chrono::steady_clock::now() - start;", "Subtracting two time points gives a duration."],
        ["const auto us = std::chrono::duration_cast<std::chrono::microseconds>(elapsed).count();", "Convert to whole microseconds and read the number."],
        ["std::cout << us << \" us\\n\";", "Print how long the step took."],
        ["constexpr auto period = 10ms;", "A typed 10-millisecond duration."],
        ["constexpr auto seconds = std::chrono::duration<double>(period).count();", "Convert to a double number of seconds (0.01)."],
      ),
      exercise:
        "Measure a loop of 1,000 sine calculations with steady_clock and print the elapsed time in microseconds. Then compute the frequency in Hz that corresponds to a 20 ms period.",
    },
    {
      title: "Multithreading: std::thread, std::mutex and std::lock_guard",
      detail: "Starting threads, joining them, data races and protecting shared data.",
      time: "60–90 min",
      concept: [
        "std::thread starts a function on a new thread. You must join() it (wait for it to finish) or detach() it before the thread object is destroyed; joining is almost always right. Threads share memory, so two threads changing the same variable without protection is a data race and is undefined behaviour.",
        "A std::mutex lets only one thread into a critical section at a time. Never call lock() and unlock() by hand; use std::lock_guard (or std::scoped_lock), which unlocks in its destructor. Keep the locked section short and never block on slow I/O while holding it. Compile with -pthread.",
      ],
      example: cpp(
        ["#include <thread>", "Header for std::thread."],
        ["#include <mutex>", "Header for std::mutex and lock_guard."],
        ["std::mutex m;", "Guards the shared counter."],
        ["int samples = 0;", "Shared data touched by two threads."],
        ["auto work = [&] {", "A lambda that each thread will run; & captures m and samples by reference."],
        ["  for (int i = 0; i < 1000; ++i) {", "Do 1000 increments."],
        ["    std::lock_guard<std::mutex> lock{m};", "Lock now; the destructor unlocks at the end of each iteration."],
        ["    ++samples;", "Safe: only one thread is here at a time."],
        ["  }", "End of the loop body."],
        ["};", "End of the lambda."],
        ["std::thread a{work}, b{work};", "Start two threads running the same work."],
        ["a.join(); b.join();", "Wait for both to finish before reading the result."],
        ["std::cout << samples << '\\n';", "Always prints 2000; without the mutex the result would vary."],
      ),
      exercise:
        "Run the example without the mutex and record the results over 10 runs. Add the lock_guard, then build with -fsanitize=thread -pthread and confirm ThreadSanitizer reports the race only in the unprotected version.",
    },
    {
      title: "Async programming: std::future and std::async",
      detail: "Running work in the background and collecting the result later.",
      time: "45–75 min",
      concept: [
        "std::async runs a function, possibly on another thread, and returns a std::future. Calling get() on the future waits for the result and rethrows any exception the function threw. Use std::launch::async to force a real thread.",
        "A future is the receiving end of a one-time result; std::promise is the sending end. Futures are good for one-off jobs such as loading a map, but for repeated events use callbacks or a queue. Do not call get() on the thread that must stay responsive.",
      ],
      example: cpp(
        ["#include <future>", "Header for std::async, std::future and std::promise."],
        ["double slow_plan(double goal) { return goal * 2.0; }", "Stand-in for a slow planner."],
        ["auto pending = std::async(std::launch::async, slow_plan, 3.0);", "Start slow_plan(3.0) on another thread immediately."],
        ["std::cout << \"planning...\\n\";", "This thread keeps working in the meantime."],
        ["double path = pending.get();", "Wait for the result (6.0); an exception would be rethrown here."],
        ["std::promise<int> p;", "The sending end of a one-time result."],
        ["std::future<int> f = p.get_future();", "The receiving end tied to the promise."],
        ["std::thread t{[&p] { p.set_value(42); }};", "Another thread fulfils the promise."],
        ["std::cout << f.get() << '\\n';", "Blocks until the value arrives, then prints 42."],
        ["t.join();", "Always join the thread before it is destroyed."],
      ),
      exercise:
        "Start three std::async jobs that each sleep 100 ms and return a number. Measure that the total time is about 100 ms, not 300 ms. Make one job throw and show where the exception appears.",
    },
    {
      title: "std::optional and std::variant",
      detail: "Values that may be missing, and values that are one of several types.",
      time: "45–75 min",
      concept: [
        "std::optional<T> holds a T or nothing, replacing magic values such as -1 for 'no reading'. Test it with if (opt) or has_value(), read it with * or value_or(default).",
        "std::variant<A, B, C> holds exactly one of several types at a time, and std::visit calls the right code for the active one. Together they give safe, self-describing types, for example a command that is either a Stop, a MoveTo or a SetSpeed.",
      ],
      example: cpp(
        ["#include <optional>", "Header for std::optional."],
        ["#include <variant>", "Header for std::variant and std::visit."],
        ["std::optional<double> reading;", "Starts empty: no value yet."],
        ["reading = 21.5;", "Now it holds a value."],
        ["std::cout << reading.value_or(-1.0) << '\\n';", "Prints 21.5; would print -1 if empty."],
        ["struct Stop {}; struct MoveTo { double x; }; struct SetSpeed { double v; };", "Three command types."],
        ["using Command = std::variant<Stop, MoveTo, SetSpeed>;", "A Command is exactly one of the three."],
        ["Command cmd = MoveTo{1.5};", "Store a MoveTo."],
        ["std::visit([](const auto& c) {", "Call the lambda with whichever alternative is stored."],
        ["  if constexpr (std::is_same_v<std::decay_t<decltype(c)>, MoveTo>) std::cout << \"move\\n\";", "Choose code by the active type at compile time (C++17 if constexpr)."],
        ["}, cmd);", "Pass the variant to visit."],
      ),
      exercise:
        "Model robot commands as std::variant<Stop, MoveTo, SetSpeed> and write a handler with std::visit that prints a description for each. Add a function returning std::optional<Command> that parses a string, and test a bad string.",
    },
    {
      title: "std::function",
      detail: "Storing any callable, callback members and the cost of type erasure.",
      time: "45–60 min",
      concept: [
        "std::function<R(Args...)> can hold any callable with that signature: a free function, a lambda or a functor. This lets a class store a callback without knowing its exact type, which is how event-driven code and many ROS 2 APIs work.",
        "std::function has a small cost (indirect call, sometimes an allocation). Use a template parameter for hot code, and std::function for stored callbacks. Check an empty function with if (callback) before calling, since calling an empty one throws.",
      ],
      example: cpp(
        ["#include <functional>", "Header for std::function."],
        ["class Button {", "A class that reports events through a callback."],
        ["public:", "Public interface."],
        ["  using Callback = std::function<void(int)>;", "Any callable taking an int and returning nothing."],
        ["  void on_press(Callback cb) { cb_ = std::move(cb); }", "Store the callback, moving it to avoid a copy."],
        ["  void press(int id) { if (cb_) cb_(id); }", "Call it, but only if one was set."],
        ["private:", "Hidden data."],
        ["  Callback cb_;", "Empty until set."],
        ["};", "End of the class."],
        ["Button b;", "Create a button with no callback."],
        ["b.on_press([](int id) { std::cout << \"button \" << id << '\\n'; });", "Register a lambda."],
        ["b.press(7);", "Triggers the callback: prints 'button 7'."],
      ),
      exercise:
        "Write an EventBus with register(std::function<void(const std::string&)>) that stores several callbacks and calls them all in publish(). Register a lambda and a free function and test both.",
    },
    {
      title: "Type traits",
      detail: "std::is_same, std::is_integral, enable_if and compile-time type questions.",
      time: "45–75 min",
      concept: [
        "The <type_traits> header lets code ask questions about types at compile time: std::is_same_v<A, B>, std::is_integral_v<T>, std::is_floating_point_v<T>, std::is_pointer_v<T>. Each has a _v shortcut for the value and a _t shortcut for transformations such as std::remove_reference_t<T>.",
        "Traits are used with static_assert (fail compilation with a message) and with if constexpr (choose code by type). They are the building blocks of generic code that you meet again in Phase 4.",
      ],
      example: cpp(
        ["#include <type_traits>", "Header with the standard traits."],
        ["static_assert(std::is_integral_v<int>, \"int is integral\");", "Compile-time check: fails to compile if the statement is false."],
        ["static_assert(!std::is_integral_v<double>, \"double is not integral\");", "The opposite check."],
        ["static_assert(std::is_same_v<std::remove_reference_t<int&>, int>, \"strip the reference\");", "remove_reference_t turns int& into int."],
        ["template <typename T>", "Start a template so the function works for many types."],
        ["std::string describe(T value) {", "Return a description that depends on the type."],
        ["  if constexpr (std::is_integral_v<T>) return \"whole number\";", "Chosen at compile time for int, long, etc."],
        ["  else if constexpr (std::is_floating_point_v<T>) return \"fraction\";", "Chosen for float and double."],
        ["  else return \"something else\";", "Fallback for all other types."],
        ["}", "End of describe."],
      ),
      exercise:
        "Write a template scale(T value, double factor) that static_asserts std::is_arithmetic_v<T>. Call it with int and double, then with std::string and read the compiler message.",
    },
    {
      title: "constexpr (C++17)",
      detail: "Computing values at compile time, constexpr functions and constexpr if.",
      time: "45–60 min",
      concept: [
        "constexpr tells the compiler a value or function can be evaluated at compile time. Compile-time results cost nothing at run time and can be used in places that need constants, such as std::array sizes and static_assert. In C++17 constexpr functions can contain loops and conditions.",
        "Use constexpr for constants (limits, conversion factors) and small pure functions. A constexpr function called with run-time arguments still works normally; it is only evaluated at compile time when all arguments are constants.",
      ],
      example: cpp(
        ["constexpr double pi = 3.14159265358979;", "A compile-time constant."],
        ["constexpr double deg_to_rad(double deg) {", "A function the compiler can run while compiling."],
        ["  return deg * pi / 180.0;", "Simple arithmetic is allowed."],
        ["}", "End of deg_to_rad."],
        ["constexpr double quarter_turn = deg_to_rad(90.0);", "Evaluated at compile time; no run-time cost."],
        ["static_assert(quarter_turn > 1.57 && quarter_turn < 1.58, \"unit conversion is wrong\");", "Compile-time proof the conversion works."],
        ["constexpr int factorial(int n) {", "C++17 allows loops in constexpr functions."],
        ["  int r = 1; for (int i = 2; i <= n; ++i) r *= i; return r;", "Multiply 2..n."],
        ["}", "End of factorial."],
        ["std::array<double, factorial(4)> table{};", "The array size (24) is computed at compile time."],
      ),
      exercise:
        "Write a constexpr function that converts encoder ticks to degrees. Use it to size a lookup table and add a static_assert for two known values. Call it once with a runtime value too.",
    },
  ],
};
