import { cpp, type CppPhase } from "./types";

export const phase6: CppPhase = {
  number: 6,
  title: "Phase 6 — C++ for ROS 2 (Pre-ROS 2 Training)",
  blurb: "Prepare your C++ brain for ROS 2's architecture: node-like classes, callbacks, events, queues and timers, all without ROS installed.",
  lessons: [
    {
      title: "Class-based node-like structures",
      detail: "A class that owns its state, publishers and timers, the shape every ROS 2 node has.",
      time: "60–90 min",
      concept: [
        "A ROS 2 node is a class that owns everything it needs (name, parameters, publishers, subscriptions, timers) and sets it up in its constructor. Practise that shape now with a plain C++ class: a name, a configuration, some state, and small methods that react to events.",
        "Keep the constructor for wiring and the methods for behaviour. Store dependencies as members so their lifetime equals the node's lifetime (RAII), and avoid globals so that several nodes can run in one process.",
      ],
      example: cpp(
        ["class TemperatureNode {", "A node-like class that owns its own name and state."],
        ["public:", "Public interface."],
        ["  explicit TemperatureNode(std::string name) : name_{std::move(name)} {}", "Store the node name; the constructor only wires things up."],
        ["  void on_sample(double celsius) {", "Behaviour: react to a new reading."],
        ["    last_ = celsius;", "Remember the latest value."],
        ["    if (celsius > limit_) std::cout << name_ << \": too hot\\n\";", "Report a problem, tagged with the node name."],
        ["  }", "End of on_sample."],
        ["  const std::string& name() const { return name_; }", "Read-only access to the name."],
        ["private:", "Hidden state."],
        ["  std::string name_;", "The node's identity."],
        ["  double limit_{80.0};", "Configured alarm limit."],
        ["  double last_{0.0};", "Most recent reading."],
        ["};", "End of the class."],
      ),
      exercise:
        "Write two node-like classes, TemperatureNode and FanNode, each with a name and a callback method. Create both in one main() and drive them with a loop of fake readings.",
    },
    {
      title: "Callbacks and lambdas",
      detail: "Passing behaviour into objects, binding member functions, and callback lifetimes.",
      time: "60–90 min",
      concept: [
        "A callback is a function you give to an object, and it calls it later when something happens. ROS 2 subscriptions and timers work this way. A lambda is the most common form, and [this] lets the callback call member functions of the node that created it.",
        "The danger is lifetime: a callback that captures this or a reference must not run after the node or variable is destroyed. Keep callbacks owned by the same object they call into, so both disappear together.",
      ],
      example: cpp(
        ["class Subscriber {", "Owns a topic name and a callback, like a ROS 2 subscription."],
        ["public:", "Public interface."],
        ["  using Callback = std::function<void(const std::string&)>;", "Any callable taking a message string."],
        ["  Subscriber(std::string topic, Callback cb) : topic_{std::move(topic)}, cb_{std::move(cb)} {}", "Store the topic and the callback."],
        ["  void deliver(const std::string& msg) const { cb_(msg); }", "Call the stored callback with a message."],
        ["private:", "Hidden state."],
        ["  std::string topic_;", "The topic name."],
        ["  Callback cb_;", "The behaviour to run."],
        ["};", "End of the class."],
        ["class Logger {", "A node that wants to receive messages."],
        ["public:", "Public interface."],
        ["  Logger() : sub_{\"/status\", [this](const std::string& m) { last_ = m; }} {}", "The lambda captures this, so it updates the Logger's own member."],
        ["  std::string last_; Subscriber sub_;", "Members: last message and the subscription that owns the lambda."],
        ["};", "End of Logger; the lambda and the object have the same lifetime."],
      ),
      exercise:
        "Build Subscriber and Logger as shown. Call deliver() three times and print last_. Then create a Subscriber whose lambda captures a local by reference and explain why calling it after the function returns would be a bug.",
    },
    {
      title: "Event-driven programming",
      detail: "An event loop, dispatching events to handlers, and never blocking inside a handler.",
      time: "60–90 min",
      concept: [
        "Event-driven programs do not run top to bottom; they wait for events (a message arrived, a timer fired, a goal was requested) and run the matching handler. A loop takes the next event and dispatches it. ROS 2's rclcpp::spin is exactly this loop.",
        "Handlers must be short. A handler that blocks or waits for another event stops every other handler from running, so long work belongs on another thread or in a state machine advanced by later events.",
      ],
      example: cpp(
        ["struct Event { std::string type; double value; };", "An event: what happened and a number."],
        ["class EventLoop {", "A tiny dispatcher."],
        ["public:", "Public interface."],
        ["  using Handler = std::function<void(const Event&)>;", "A handler takes an event."],
        ["  void on(const std::string& type, Handler h) { handlers_[type] = std::move(h); }", "Register one handler per event type."],
        ["  void post(Event e) { queue_.push(std::move(e)); }", "Add an event to the waiting queue."],
        ["  void run_pending() {", "Process everything queued so far."],
        ["    while (!queue_.empty()) {", "Until the queue is empty..."],
        ["      Event e = std::move(queue_.front()); queue_.pop();", "Take the oldest event."],
        ["      if (auto it = handlers_.find(e.type); it != handlers_.end()) it->second(e);", "Dispatch it to its handler, if one is registered."],
        ["    }", "End of the while loop."],
        ["  }", "End of run_pending."],
        ["private:", "Hidden state."],
        ["  std::map<std::string, Handler> handlers_; std::queue<Event> queue_;", "Handlers by type and the queue of waiting events."],
        ["};", "End of the class."],
      ),
      exercise:
        "Register handlers for 'temperature' and 'fault' on the loop, post five events, and print what each handler receives. Add a handler that posts a new event and confirm it runs in the same run_pending() call.",
    },
    {
      title: "Asynchronous patterns",
      detail: "Futures, worker threads and posting results back to the main loop safely.",
      time: "60–90 min",
      concept: [
        "Asynchronous code starts work and continues without waiting. Common shapes are a future you check later, a worker thread that pushes results onto a queue, and a callback fired on completion. All of them must protect shared data and avoid blocking the event loop.",
        "A robust pattern is: slow work runs on a worker, and its result is posted as an event to the main loop, which handles it on the loop thread. This keeps handlers single-threaded and easy to reason about, and is how ROS 2 action servers are structured.",
      ],
      example: cpp(
        ["std::mutex m;", "Guards the list of finished results."],
        ["std::vector<double> results;", "Results posted by the worker."],
        ["std::thread worker{[&] {", "Start slow work on another thread."],
        ["  std::this_thread::sleep_for(std::chrono::milliseconds(50));", "Pretend to plan a path for 50 ms."],
        ["  std::lock_guard<std::mutex> lock{m};", "Lock before touching the shared list."],
        ["  results.push_back(3.14);", "Post the result."],
        ["}};", "End of the worker; the lock is released here."],
        ["worker.join();", "Wait for the worker (a real program would poll or use a condition variable)."],
        ["{", "A small scope so the lock is released as soon as we are done."],
        ["  std::lock_guard<std::mutex> lock{m};", "Lock while reading."],
        ["  for (double r : results) std::cout << r << '\\n';", "Handle each result on the main thread."],
        ["}", "End of the scope; unlock."],
      ),
      exercise:
        "Start three worker threads that each post a result after a different delay. Handle the results on the main thread in the order they arrive, and confirm ThreadSanitizer reports no race.",
    },
    {
      title: "Clean API design",
      detail: "Small interfaces, strong types, const-correctness and hard-to-misuse functions.",
      time: "45–75 min",
      concept: [
        "A good API makes correct use easy and incorrect use hard. Use distinct types instead of raw doubles for different units, explicit constructors so a number is never converted by accident, const for anything that does not change, and enums instead of booleans whose meaning is unclear.",
        "Keep the public surface small. Return values instead of using output parameters, document units and error behaviour, and mark results that must not be ignored with [[nodiscard]]. rclcpp's own API follows these habits.",
      ],
      example: cpp(
        ["struct Meters { explicit Meters(double v) : value{v} {} double value; };", "A distinct type for distances; explicit stops implicit conversion from a plain double."],
        ["struct Seconds { explicit Seconds(double v) : value{v} {} double value; };", "A distinct type for times."],
        ["enum class Direction { forward, backward };", "Clear names instead of a bool like true/false."],
        ["[[nodiscard]] double speed(Meters d, Seconds t) { return d.value / t.value; }", "Units are in the signature and the result cannot be silently ignored."],
        ["double v = speed(Meters{2.0}, Seconds{4.0});", "Reads clearly: 0.5 m/s."],
        ["// speed(Seconds{4.0}, Meters{2.0});", "Would not compile: the arguments are swapped, so the bug is caught at compile time."],
        ["void drive(Direction dir, double speed_mps);", "drive(Direction::forward, 0.5) documents itself; drive(true, 0.5) does not."],
      ),
      exercise:
        "Redesign move(double, double, bool) into an API using Meters, Radians and an enum class. Write three calls that compile and three misuses that the compiler must reject.",
    },
    {
      title: "Logging patterns",
      detail: "Log levels, structured messages, throttling and keeping logging out of hot loops.",
      time: "45–75 min",
      concept: [
        "Logging is how a running robot explains itself. Use levels (debug, info, warn, error, fatal), include the component name and the values that matter, and make messages searchable. ROS 2 provides RCLCPP_INFO, RCLCPP_WARN and RCLCPP_ERROR with the same idea.",
        "Logging costs time. Do not print inside a fast control loop; throttle repeated messages (once per second) and keep a level filter so debug output can be turned off. Never log secrets, and always log the reason with the error.",
      ],
      example: cpp(
        ["enum class Level { debug, info, warn, error };", "Ordered severity levels."],
        ["class Logger {", "A tiny logger with a level filter."],
        ["public:", "Public interface."],
        ["  explicit Logger(std::string name, Level min = Level::info) : name_{std::move(name)}, min_{min} {}", "Store the component name and the lowest level to print."],
        ["  void log(Level lvl, const std::string& msg) const {", "Print a message if it is important enough."],
        ["    if (lvl < min_) return;", "Filtered out: cheap and silent."],
        ["    std::cerr << '[' << name_ << \"] \" << msg << '\\n';", "Write to stderr with the component name."],
        ["  }", "End of log."],
        ["private:", "Hidden state."],
        ["  std::string name_; Level min_;", "Component name and threshold."],
        ["};", "End of the class."],
        ["Logger log{\"arm_driver\"};", "Create a logger for one component."],
        ["log.log(Level::warn, \"joint 3 near limit: 1.48 rad\");", "A useful message: what, where and the value."],
      ),
      exercise:
        "Add a throttled warn() to the logger that prints at most once per second using steady_clock. Call it 1,000 times in a loop and confirm it printed only a few lines.",
    },
    {
      title: "Configuration structs",
      detail: "Grouping settings in a struct, defaults, validation and loading from a file or map.",
      time: "45–75 min",
      concept: [
        "A configuration struct gathers all settings in one place with defaults: publish rate, limits, frame names. It is easy to pass around, to print, and to compare in tests. Validate it once, when it is loaded, so the rest of the program can trust it.",
        "In ROS 2 the values arrive as parameters that you declare and read into a struct like this. Building the struct and its validation now makes the later parameter code short and safe.",
      ],
      example: cpp(
        ["struct ArmConfig {", "All settings of the arm driver in one type."],
        ["  std::string frame{\"base_link\"};", "Default coordinate frame name."],
        ["  double rate_hz{50.0};", "Default control rate."],
        ["  double max_speed{1.2};", "Default speed limit in rad/s."],
        ["};", "End of the struct."],
        ["std::optional<std::string> validate(const ArmConfig& c) {", "Return an error message, or nothing if the config is fine."],
        ["  if (c.rate_hz <= 0.0) return \"rate_hz must be positive\";", "Reject nonsense rates."],
        ["  if (c.max_speed <= 0.0) return \"max_speed must be positive\";", "Reject nonsense limits."],
        ["  return std::nullopt;", "No error."],
        ["}", "End of validate."],
        ["ArmConfig cfg; cfg.rate_hz = 100.0;", "Start from defaults and override one field."],
        ["if (auto err = validate(cfg)) std::cerr << *err << '\\n';", "Report the first problem, if any."],
      ),
      exercise:
        "Write a function that fills ArmConfig from a std::map<std::string, std::string>, keeping defaults for missing keys and reporting a clear error for a value that is not a number. Test three inputs.",
    },
    {
      title: "Thread-safe queues",
      detail: "A blocking queue with a mutex and condition variable for passing work between threads.",
      time: "60–90 min",
      concept: [
        "A thread-safe queue lets a producer thread push items and a consumer thread pop them, with the mutex hidden inside the class. A std::condition_variable lets the consumer sleep until an item arrives instead of burning CPU in a loop.",
        "Always wait with a predicate (cv.wait(lock, [] { return !q.empty(); })) because threads can wake spuriously. Add a close() flag so consumers can finish cleanly at shutdown. ROS 2 executors use queues of ready callbacks the same way.",
      ],
      example: cpp(
        ["template <typename T>", "A queue for any item type."],
        ["class SafeQueue {", "Thread-safe from the outside; the mutex is an implementation detail."],
        ["public:", "Public interface."],
        ["  void push(T v) {", "Called by producer threads."],
        ["    { std::lock_guard<std::mutex> lock{m_}; q_.push(std::move(v)); }", "Lock only long enough to add the item."],
        ["    cv_.notify_one();", "Wake one waiting consumer."],
        ["  }", "End of push."],
        ["  T pop() {", "Called by a consumer; blocks until an item exists."],
        ["    std::unique_lock<std::mutex> lock{m_};", "unique_lock is needed because wait() unlocks and relocks."],
        ["    cv_.wait(lock, [this] { return !q_.empty(); });", "Sleep until the queue is not empty (checked again after each wake-up)."],
        ["    T v = std::move(q_.front()); q_.pop(); return v;", "Take the oldest item."],
        ["  }", "End of pop."],
        ["private:", "Hidden state."],
        ["  std::mutex m_; std::condition_variable cv_; std::queue<T> q_;", "The lock, the wake-up signal and the storage."],
        ["};", "End of the class."],
      ),
      exercise:
        "Use SafeQueue<int> with one producer thread pushing 1..100 and one consumer summing them (the result should be 5050). Add a close() method so the consumer exits, then run the program under ThreadSanitizer.",
    },
    {
      title: "Timers and periodic tasks",
      detail: "Fixed-rate loops with steady_clock and sleep_until, without drift.",
      time: "45–75 min",
      concept: [
        "A periodic task runs at a fixed rate, such as 50 Hz (every 20 ms). Do not sleep for 20 ms after each run, because the work time is added and the loop drifts. Instead compute the next deadline from the previous deadline and sleep_until it.",
        "Measure how late each cycle actually starts; that jitter tells you whether the rate is realistic. A ROS 2 timer does this for you: you give it a period and a callback, and the executor calls the callback each time.",
      ],
      example: cpp(
        ["using clock = std::chrono::steady_clock;", "A monotonic clock that never goes backwards."],
        ["constexpr auto period = std::chrono::milliseconds(20);", "50 Hz."],
        ["auto next = clock::now() + period;", "The first deadline."],
        ["for (int i = 0; i < 5; ++i) {", "Run five cycles."],
        ["  tick(i);", "The task to run each cycle."],
        ["  std::this_thread::sleep_until(next);", "Sleep until the absolute deadline, not for a fixed time."],
        ["  const auto late = clock::now() - next;", "How far past the deadline we woke up."],
        ["  next += period;", "Advance the schedule from the previous deadline, so errors do not accumulate."],
        ["  std::cout << std::chrono::duration_cast<std::chrono::microseconds>(late).count() << \" us late\\n\";", "Report the wake-up delay in microseconds."],
        ["}", "End of the loop."],
      ),
      exercise:
        "Run a 100 Hz loop for 10 seconds, store each cycle's lateness, and print the worst and average value after the loop (not inside it). Then replace sleep_until with sleep_for(period) and compare the total elapsed time.",
    },
  ],
};
