/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CoursesCppAdvancedRouteImport } from './routes/courses.cpp-advanced'
import { Route as CoursesCppBeginnerRouteImport } from './routes/courses.cpp-beginner'
import { Route as CoursesCppIntermediateRouteImport } from './routes/courses.cpp-intermediate'
import { Route as CoursesIndustrialRobotsRouteImport } from './routes/courses.industrial-robots'
import { Route as CoursesRos2LyricalRouteImport } from './routes/courses.ros2-lyrical'
import { Route as CoursesUbuntuLinuxRouteImport } from './routes/courses.ubuntu-linux'
import { Route as LabsIndexRouteImport } from './routes/labs.index'
import { Route as LabsLabSlugRouteImport } from './routes/labs.$labSlug'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeExerciseIdRouteImport } from './routes/practice.$exerciseId'
import { Route as LessonsCourseSlugLessonSlugRouteImport } from './routes/lessons.$courseSlug.$lessonSlug'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCppAdvancedRoute = CoursesCppAdvancedRouteImport.update({
  id: '/courses/cpp-advanced',
  path: '/courses/cpp-advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCppBeginnerRoute = CoursesCppBeginnerRouteImport.update({
  id: '/courses/cpp-beginner',
  path: '/courses/cpp-beginner',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCppIntermediateRoute = CoursesCppIntermediateRouteImport.update({
  id: '/courses/cpp-intermediate',
  path: '/courses/cpp-intermediate',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndustrialRobotsRoute = CoursesIndustrialRobotsRouteImport.update({
  id: '/courses/industrial-robots',
  path: '/courses/industrial-robots',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRos2LyricalRoute = CoursesRos2LyricalRouteImport.update({
  id: '/courses/ros2-lyrical',
  path: '/courses/ros2-lyrical',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesUbuntuLinuxRoute = CoursesUbuntuLinuxRouteImport.update({
  id: '/courses/ubuntu-linux',
  path: '/courses/ubuntu-linux',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsIndexRoute = LabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabsRoute,
} as any)
const LabsLabSlugRoute = LabsLabSlugRouteImport.update({
  id: '/$labSlug',
  path: '/$labSlug',
  getParentRoute: () => LabsRoute,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeExerciseIdRoute = PracticeExerciseIdRouteImport.update({
  id: '/$exerciseId',
  path: '/$exerciseId',
  getParentRoute: () => PracticeRoute,
} as any)
const LessonsCourseSlugLessonSlugRoute =
  LessonsCourseSlugLessonSlugRouteImport.update({
    id: '/lessons/$courseSlug/$lessonSlug',
    path: '/lessons/$courseSlug/$lessonSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/labs': typeof LabsRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/courses/cpp-advanced': typeof CoursesCppAdvancedRoute
  '/courses/cpp-beginner': typeof CoursesCppBeginnerRoute
  '/courses/cpp-intermediate': typeof CoursesCppIntermediateRoute
  '/courses/industrial-robots': typeof CoursesIndustrialRobotsRoute
  '/courses/ros2-lyrical': typeof CoursesRos2LyricalRoute
  '/courses/ubuntu-linux': typeof CoursesUbuntuLinuxRoute
  '/labs/$labSlug': typeof LabsLabSlugRoute
  '/practice/$exerciseId': typeof PracticeExerciseIdRoute
  '/labs/': typeof LabsIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/lessons/$courseSlug/$lessonSlug': typeof LessonsCourseSlugLessonSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/courses/cpp-advanced': typeof CoursesCppAdvancedRoute
  '/courses/cpp-beginner': typeof CoursesCppBeginnerRoute
  '/courses/cpp-intermediate': typeof CoursesCppIntermediateRoute
  '/courses/industrial-robots': typeof CoursesIndustrialRobotsRoute
  '/courses/ros2-lyrical': typeof CoursesRos2LyricalRoute
  '/courses/ubuntu-linux': typeof CoursesUbuntuLinuxRoute
  '/labs/$labSlug': typeof LabsLabSlugRoute
  '/practice/$exerciseId': typeof PracticeExerciseIdRoute
  '/labs': typeof LabsIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/lessons/$courseSlug/$lessonSlug': typeof LessonsCourseSlugLessonSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/labs': typeof LabsRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/courses/cpp-advanced': typeof CoursesCppAdvancedRoute
  '/courses/cpp-beginner': typeof CoursesCppBeginnerRoute
  '/courses/cpp-intermediate': typeof CoursesCppIntermediateRoute
  '/courses/industrial-robots': typeof CoursesIndustrialRobotsRoute
  '/courses/ros2-lyrical': typeof CoursesRos2LyricalRoute
  '/courses/ubuntu-linux': typeof CoursesUbuntuLinuxRoute
  '/labs/$labSlug': typeof LabsLabSlugRoute
  '/practice/$exerciseId': typeof PracticeExerciseIdRoute
  '/labs/': typeof LabsIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/lessons/$courseSlug/$lessonSlug': typeof LessonsCourseSlugLessonSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/labs'
    | '/practice'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/terms'
    | '/checkout/success'
    | '/courses/cpp-advanced'
    | '/courses/cpp-beginner'
    | '/courses/cpp-intermediate'
    | '/courses/industrial-robots'
    | '/courses/ros2-lyrical'
    | '/courses/ubuntu-linux'
    | '/labs/$labSlug'
    | '/practice/$exerciseId'
    | '/labs/'
    | '/practice/'
    | '/lessons/$courseSlug/$lessonSlug'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/terms'
    | '/checkout/success'
    | '/courses/cpp-advanced'
    | '/courses/cpp-beginner'
    | '/courses/cpp-intermediate'
    | '/courses/industrial-robots'
    | '/courses/ros2-lyrical'
    | '/courses/ubuntu-linux'
    | '/labs/$labSlug'
    | '/practice/$exerciseId'
    | '/labs'
    | '/practice'
    | '/lessons/$courseSlug/$lessonSlug'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/labs'
    | '/practice'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/terms'
    | '/checkout/success'
    | '/courses/cpp-advanced'
    | '/courses/cpp-beginner'
    | '/courses/cpp-intermediate'
    | '/courses/industrial-robots'
    | '/courses/ros2-lyrical'
    | '/courses/ubuntu-linux'
    | '/labs/$labSlug'
    | '/practice/$exerciseId'
    | '/labs/'
    | '/practice/'
    | '/lessons/$courseSlug/$lessonSlug'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  LabsRoute: typeof LabsRouteWithChildren
  PracticeRoute: typeof PracticeRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CoursesCppAdvancedRoute: typeof CoursesCppAdvancedRoute
  CoursesCppBeginnerRoute: typeof CoursesCppBeginnerRoute
  CoursesCppIntermediateRoute: typeof CoursesCppIntermediateRoute
  CoursesIndustrialRobotsRoute: typeof CoursesIndustrialRobotsRoute
  CoursesRos2LyricalRoute: typeof CoursesRos2LyricalRoute
  CoursesUbuntuLinuxRoute: typeof CoursesUbuntuLinuxRoute
  LessonsCourseSlugLessonSlugRoute: typeof LessonsCourseSlugLessonSlugRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/cpp-advanced': {
      id: '/courses/cpp-advanced'
      path: '/courses/cpp-advanced'
      fullPath: '/courses/cpp-advanced'
      preLoaderRoute: typeof CoursesCppAdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/cpp-beginner': {
      id: '/courses/cpp-beginner'
      path: '/courses/cpp-beginner'
      fullPath: '/courses/cpp-beginner'
      preLoaderRoute: typeof CoursesCppBeginnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/cpp-intermediate': {
      id: '/courses/cpp-intermediate'
      path: '/courses/cpp-intermediate'
      fullPath: '/courses/cpp-intermediate'
      preLoaderRoute: typeof CoursesCppIntermediateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/industrial-robots': {
      id: '/courses/industrial-robots'
      path: '/courses/industrial-robots'
      fullPath: '/courses/industrial-robots'
      preLoaderRoute: typeof CoursesIndustrialRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/ros2-lyrical': {
      id: '/courses/ros2-lyrical'
      path: '/courses/ros2-lyrical'
      fullPath: '/courses/ros2-lyrical'
      preLoaderRoute: typeof CoursesRos2LyricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/ubuntu-linux': {
      id: '/courses/ubuntu-linux'
      path: '/courses/ubuntu-linux'
      fullPath: '/courses/ubuntu-linux'
      preLoaderRoute: typeof CoursesUbuntuLinuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/': {
      id: '/labs/'
      path: '/'
      fullPath: '/labs/'
      preLoaderRoute: typeof LabsIndexRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/$labSlug': {
      id: '/labs/$labSlug'
      path: '/$labSlug'
      fullPath: '/labs/$labSlug'
      preLoaderRoute: typeof LabsLabSlugRouteImport
      parentRoute: typeof LabsRoute
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/$exerciseId': {
      id: '/practice/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/practice/$exerciseId'
      preLoaderRoute: typeof PracticeExerciseIdRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/lessons/$courseSlug/$lessonSlug': {
      id: '/lessons/$courseSlug/$lessonSlug'
      path: '/lessons/$courseSlug/$lessonSlug'
      fullPath: '/lessons/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof LessonsCourseSlugLessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LabsRouteChildren {
  LabsLabSlugRoute: typeof LabsLabSlugRoute
  LabsIndexRoute: typeof LabsIndexRoute
}

const LabsRouteChildren: LabsRouteChildren = {
  LabsLabSlugRoute: LabsLabSlugRoute,
  LabsIndexRoute: LabsIndexRoute,
}

const LabsRouteWithChildren = LabsRoute._addFileChildren(LabsRouteChildren)

interface PracticeRouteChildren {
  PracticeExerciseIdRoute: typeof PracticeExerciseIdRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeExerciseIdRoute: PracticeExerciseIdRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  LabsRoute: LabsRouteWithChildren,
  PracticeRoute: PracticeRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CoursesCppAdvancedRoute: CoursesCppAdvancedRoute,
  CoursesCppBeginnerRoute: CoursesCppBeginnerRoute,
  CoursesCppIntermediateRoute: CoursesCppIntermediateRoute,
  CoursesIndustrialRobotsRoute: CoursesIndustrialRobotsRoute,
  CoursesRos2LyricalRoute: CoursesRos2LyricalRoute,
  CoursesUbuntuLinuxRoute: CoursesUbuntuLinuxRoute,
  LessonsCourseSlugLessonSlugRoute: LessonsCourseSlugLessonSlugRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
